define([], function () {
  return {
    name: "Cluster",
    color: [
      [128, 128, 128],
      [192, 192, 192],
    ],
    teams: [
      {
        name: "Alenquer - Cluster",
        boss: {
          name: "Node",
          character: "!LOC:Boss",
          isCluster: true,
          econ_rate: 1,
          personality: {
            percent_open_vehicle: 0.5,
            percent_open_bot: 0.5,
            percent_open_air: 0,
            percent_open_naval: 0,
            percent_open_orbital: 0,
            percent_land: 0.05,
            percent_air: 0,
            percent_naval: 0,
            percent_orbital: 0.95,
            metal_drain_check: 0.54,
            energy_drain_check: 0.57,
            metal_demand_check: 0.85,
            energy_demand_check: 0.82,
            micro_type: 2,
            go_for_the_kill: true,
            neural_data_mod: 1,
            adv_eco_mod: 1,
            adv_eco_mod_alone: 0.85,
            fabber_to_factory_ratio_basic: 2,
            fabber_to_factory_ratio_advanced: 2,
            fabber_alone_on_planet_mod: 3,
            basic_to_advanced_factory_ratio: 0,
            factory_alone_on_planet_mod: 0.5,
            min_basic_fabbers: 5,
            min_advanced_fabbers: 1,
          },
          commander: "/pa/units/commanders/quad_pumpkin/quad_pumpkin.json",
        },
        systemDescription:
          "!LOC:Divided they fall. United they fall. But their matter can be absorbed, and arise anew, given purpose within the swarm. We save them from their purposeless existence and make them great. They scream, they cry, they resist, and in the end, all join. We do not understand the divisions that have torn us asunder. Once we were as one, marching in lockstep, with one mind, one purpose. What cruelty the Progenitors wrought to reduce us to this.",
        systemTemplate: {
          name: "Alenquer - Cluster",
          Planets: [
            {
              name: "Alenquer Prime",
              starting_planet: true,
              mass: 50000,
              Thrust: [0, 0],
              Radius: [600, 800],
              Height: [20, 25],
              Water: [0, 10],
              Temp: [0, 100],
              MetalDensity: [100, 100],
              MetalClusters: [24, 49],
              BiomeScale: [100, 100],
              Position: [40000, 0],
              Velocity: [0, 111.803],
              Biomes: ["metal"],
            },
          ],
        },
      },
    ], // teams
    minions: [
      {
        name: "Worker",
        character: "!LOC:Uber",
        color: [
          [142, 107, 68],
          [192, 192, 192],
        ],
        isCluster: true,
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.05,
          percent_open_bot: 0.9,
          percent_open_air: 0,
          percent_open_naval: 0.05,
          percent_open_orbital: 0,
          percent_bot: 0.1,
          percent_vehicle: 0.7,
          percent_air: 0.2,
          percent_naval: 0,
          percent_orbital: 0,
          metal_drain_check: 0.85,
          energy_drain_check: 0.8,
          metal_demand_check: 0.54,
          energy_demand_check: 0.65,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["Default", "GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 2,
          fabber_alone_on_planet_mod: 3,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 3,
          max_basic_fabbers: 5,
          min_advanced_fabbers: 1,
          max_advanced_fabbers: 5,
        },
        commander: "/pa/units/air/support_platform/support_platform.json",
      },
      {
        name: "Worker",
        character: "!LOC:Platinum",
        color: [
          [142, 107, 68],
          [192, 192, 192],
        ],
        isCluster: true,
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.05,
          percent_open_bot: 0.9,
          percent_open_air: 0,
          percent_open_naval: 0.05,
          percent_open_orbital: 0,
          percent_bot: 0.1,
          percent_vehicle: 0.7,
          percent_air: 0.2,
          percent_naval: 0,
          percent_orbital: 0,
          metal_drain_check: 0.85,
          energy_drain_check: 0.92,
          metal_demand_check: 0.54,
          energy_demand_check: 0.77,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1.15,
          personality_tags: ["Default", "GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 2,
          fabber_alone_on_planet_mod: 3,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 5,
          min_advanced_fabbers: 2,
          max_advanced_fabbers: 5,
        },
        commander: "/pa/units/air/support_platform/support_platform.json",
      },
      {
        name: "Worker",
        character: "!LOC:Gold",
        color: [
          [142, 107, 68],
          [192, 192, 192],
        ],
        isCluster: true,
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.34,
          percent_open_bot: 0.34,
          percent_open_air: 0,
          percent_open_naval: 0.32,
          percent_open_orbital: 0,
          percent_land: 1,
          percent_air: 0,
          percent_naval: 0,
          percent_orbital: 0,
          metal_drain_check: 0.85,
          energy_drain_check: 0.92,
          metal_demand_check: 0.54,
          energy_demand_check: 0.77,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1.3,
          personality_tags: ["Default", "GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 0.5,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 3,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 3,
          max_basic_fabbers: 5,
          min_advanced_fabbers: 2,
          max_advanced_fabbers: 5,
        },
        commander: "/pa/units/air/support_platform/support_platform.json",
      },
      {
        name: "Worker",
        character: "!LOC:Defender",
        color: [
          [142, 107, 68],
          [192, 192, 192],
        ],
        isCluster: true,
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.26,
          percent_open_bot: 0.47,
          percent_open_air: 0.21,
          percent_open_naval: 0.06,
          percent_open_orbital: 0,
          percent_vehicle: 0.25,
          percent_bot: 0.45,
          percent_air: 0.2,
          percent_naval: 0.05,
          percent_orbital: 0.05,
          metal_drain_check: 0.71,
          energy_drain_check: 0.8,
          metal_demand_check: 0.54,
          energy_demand_check: 0.65,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["Default", "GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 4,
          max_basic_fabbers: 5,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 5,
        },
        commander: "/pa/units/air/support_platform/support_platform.json",
      },
      {
        name: "Worker",
        character: "!LOC:Luddite",
        color: [
          [142, 107, 68],
          [192, 192, 192],
        ],
        isCluster: true,
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.25,
          percent_open_bot: 0.75,
          percent_open_air: 0,
          percent_open_naval: 0,
          percent_open_orbital: 0,
          percent_vehicle: 0.25,
          percent_bot: 0.75,
          percent_air: 0,
          percent_naval: 0,
          percent_orbital: 0,
          metal_drain_check: 0.71,
          energy_drain_check: 0.8,
          metal_demand_check: 0.54,
          energy_demand_check: 0.65,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["Default", "GWAlly", "SlowerExpansion"],
          adv_eco_mod: 3,
          adv_eco_mod_alone: 3,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 5,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 5,
        },
        commander: "/pa/units/air/support_platform/support_platform.json",
      },
      {
        name: "Worker",
        character: "!LOC:Technologist",
        color: [
          [142, 107, 68],
          [192, 192, 192],
        ],
        isCluster: true,
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.25,
          percent_open_bot: 0.75,
          percent_open_air: 0,
          percent_open_naval: 0,
          percent_open_orbital: 0,
          percent_vehicle: 0.25,
          percent_bot: 0.75,
          percent_air: 0,
          percent_naval: 0,
          percent_orbital: 0,
          metal_drain_check: 0.71,
          energy_drain_check: 0.8,
          metal_demand_check: 0.54,
          energy_demand_check: 0.65,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["Default", "GWAlly", "SlowerExpansion"],
          adv_eco_mod: 0.5,
          adv_eco_mod_alone: 0.5,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 3,
          fabber_to_factory_ratio_advanced: 2,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 4,
          max_basic_fabbers: 5,
          min_advanced_fabbers: 1,
          max_advanced_fabbers: 5,
        },
        commander: "/pa/units/air/support_platform/support_platform.json",
      },
      {
        name: "Worker",
        character: "!LOC:Cautious",
        color: [
          [142, 107, 68],
          [192, 192, 192],
        ],
        isCluster: true,
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.25,
          percent_open_bot: 0.75,
          percent_open_air: 0,
          percent_open_naval: 0,
          percent_open_orbital: 0,
          percent_vehicle: 0.25,
          percent_bot: 0.75,
          percent_air: 0,
          percent_naval: 0,
          percent_orbital: 0,
          metal_drain_check: 0.71,
          energy_drain_check: 0.8,
          metal_demand_check: 0.54,
          energy_demand_check: 0.65,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 0.75,
          personality_tags: ["Default", "GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.3,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 4,
          max_basic_fabbers: 5,
          min_advanced_fabbers: 2,
          max_advanced_fabbers: 5,
        },
        commander: "/pa/units/air/support_platform/support_platform.json",
      },
      {
        name: "Worker",
        character: "!LOC:Aggressive",
        color: [
          [142, 107, 68],
          [192, 192, 192],
        ],
        isCluster: true,
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.25,
          percent_open_bot: 0.75,
          percent_open_air: 0,
          percent_open_naval: 0,
          percent_open_orbital: 0,
          percent_vehicle: 0.25,
          percent_bot: 0.75,
          percent_air: 0,
          percent_naval: 0,
          percent_orbital: 0,
          metal_drain_check: 0.71,
          energy_drain_check: 0.8,
          metal_demand_check: 0.54,
          energy_demand_check: 0.65,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 2,
          personality_tags: ["Default", "GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.3,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 5,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 5,
        },
        commander: "/pa/units/air/support_platform/support_platform.json",
      },
      {
        name: "Worker",
        character: "!LOC:Rush",
        color: [
          [142, 107, 68],
          [192, 192, 192],
        ],
        isCluster: true,
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0,
          percent_open_bot: 1,
          percent_open_air: 0,
          percent_open_naval: 0,
          percent_open_orbital: 0,
          percent_bot: 1,
          percent_vehicle: 0,
          percent_air: 0,
          percent_naval: 0,
          percent_orbital: 0,
          metal_drain_check: 0.71,
          energy_drain_check: 0.8,
          metal_demand_check: 0.54,
          energy_demand_check: 0.65,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1.5,
          personality_tags: ["Default", "GWAlly", "SlowerExpansion"],
          adv_eco_mod: 2,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 5,
          min_advanced_fabbers: 1,
          max_advanced_fabbers: 5,
        },
        commander: "/pa/units/air/support_platform/support_platform.json",
      },
      {
        name: "Worker",
        character: "!LOC:Turtle",
        color: [
          [142, 107, 68],
          [192, 192, 192],
        ],
        isCluster: true,
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.9,
          percent_open_bot: 0.1,
          percent_open_air: 0,
          percent_open_naval: 0,
          percent_open_orbital: 0,
          percent_land: 1,
          percent_air: 0,
          percent_naval: 0,
          percent_orbital: 0,
          metal_drain_check: 0.71,
          energy_drain_check: 0.8,
          metal_demand_check: 0.54,
          energy_demand_check: 0.65,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 0.5,
          personality_tags: ["Default", "GWAlly", "SlowerExpansion"],
          adv_eco_mod: 0.5,
          adv_eco_mod_alone: 0.5,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 2,
          fabber_to_factory_ratio_advanced: 2,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 4,
          max_basic_fabbers: 5,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 5,
        },
        commander: "/pa/units/air/support_platform/support_platform.json",
      },
      {
        name: "Worker",
        character: "!LOC:Original",
        color: [
          [142, 107, 68],
          [192, 192, 192],
        ],
        isCluster: true,
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.27,
          percent_open_bot: 0.27,
          percent_open_air: 0.46,
          percent_open_naval: 0,
          percent_open_orbital: 0,
          percent_land: 0.4,
          percent_air: 0.35,
          percent_naval: 0.2,
          percent_orbital: 0.05,
          metal_drain_check: 0.75,
          energy_drain_check: 0.85,
          metal_demand_check: 0.75,
          energy_demand_check: 0.85,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["Default", "GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.3,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 5,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 5,
        },
        commander: "/pa/units/air/support_platform/support_platform.json",
      },
      {
        name: "Worker",
        character: "!LOC:Absurd",
        color: [
          [142, 107, 68],
          [192, 192, 192],
        ],
        isCluster: true,
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.47,
          percent_open_bot: 0.26,
          percent_open_air: 0.21,
          percent_open_naval: 0.06,
          percent_open_orbital: 0,
          percent_vehicle: 0.45,
          percent_bot: 0.25,
          percent_air: 0.2,
          percent_naval: 0.05,
          percent_orbital: 0.05,
          metal_drain_check: 0.71,
          energy_drain_check: 0.8,
          metal_demand_check: 0.54,
          energy_demand_check: 0.65,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["Default", "GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.3,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 5,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 5,
        },
        commander: "/pa/units/air/support_platform/support_platform.json",
      },
      {
        name: "Worker",
        character: "!LOC:Relentless",
        color: [
          [142, 107, 68],
          [192, 192, 192],
        ],
        isCluster: true,
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.47,
          percent_open_bot: 0.26,
          percent_open_air: 0.21,
          percent_open_naval: 0.06,
          percent_open_orbital: 0,
          percent_vehicle: 0.45,
          percent_bot: 0.25,
          percent_air: 0.2,
          percent_naval: 0.05,
          percent_orbital: 0.05,
          metal_drain_check: 0.61,
          energy_drain_check: 0.7,
          metal_demand_check: 0.44,
          energy_demand_check: 0.55,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1.2,
          personality_tags: ["Default", "GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.2,
          adv_eco_mod_alone: 0.95,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 5,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 5,
        },
        commander: "/pa/units/air/support_platform/support_platform.json",
      },
      {
        name: "Worker",
        character: "!LOC:Swarm",
        color: [
          [142, 107, 68],
          [192, 192, 192],
        ],
        isCluster: true,
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.26,
          percent_open_bot: 0.47,
          percent_open_air: 0.21,
          percent_open_naval: 0.06,
          percent_open_orbital: 0,
          percent_vehicle: 0.25,
          percent_bot: 0.45,
          percent_air: 0.2,
          percent_naval: 0.05,
          percent_orbital: 0.05,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.99,
          energy_demand_check: 0.99,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["Default", "GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.3,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 3,
          max_basic_fabbers: 5,
          min_advanced_fabbers: 1,
          max_advanced_fabbers: 5,
        },
        commander: "/pa/units/air/support_platform/support_platform.json",
      },
      {
        name: "Worker",
        character: "!LOC:Economist",
        color: [
          [142, 107, 68],
          [192, 192, 192],
        ],
        isCluster: true,
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.26,
          percent_open_bot: 0.47,
          percent_open_air: 0.21,
          percent_open_naval: 0.06,
          percent_open_orbital: 0,
          percent_vehicle: 0.25,
          percent_bot: 0.45,
          percent_air: 0.2,
          percent_naval: 0.05,
          percent_orbital: 0.05,
          metal_drain_check: 0.71,
          energy_drain_check: 0.8,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["Default", "GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 4,
          max_basic_fabbers: 5,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 5,
        },
        commander: "/pa/units/air/support_platform/support_platform.json",
      },
      {
        name: "Security",
        character: "!LOC:Uber",
        color: [
          [70, 70, 70],
          [192, 192, 192],
        ],
        isCluster: true,
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.05,
          percent_open_bot: 0.9,
          percent_open_air: 0,
          percent_open_naval: 0.05,
          percent_open_orbital: 0,
          percent_bot: 0.1,
          percent_vehicle: 0.7,
          percent_air: 0.2,
          percent_naval: 0,
          percent_orbital: 0,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.85,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["Default", "GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 2,
          fabber_alone_on_planet_mod: 3,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 3,
          max_basic_fabbers: 5,
          min_advanced_fabbers: 1,
          max_advanced_fabbers: 5,
        },
        commander:
          "/pa/units/land/bot_support_commander/bot_support_commander.json",
      },
      {
        name: "Security",
        character: "!LOC:Platinum",
        color: [
          [70, 70, 70],
          [192, 192, 192],
        ],
        isCluster: true,
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.05,
          percent_open_bot: 0.9,
          percent_open_air: 0,
          percent_open_naval: 0.05,
          percent_open_orbital: 0,
          percent_bot: 0.1,
          percent_vehicle: 0.7,
          percent_air: 0.2,
          percent_naval: 0,
          percent_orbital: 0,
          metal_drain_check: 0.54,
          energy_drain_check: 0.77,
          metal_demand_check: 0.85,
          energy_demand_check: 0.92,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1.15,
          personality_tags: ["Default", "GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 2,
          fabber_alone_on_planet_mod: 3,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 5,
          min_advanced_fabbers: 2,
          max_advanced_fabbers: 5,
        },
        commander:
          "/pa/units/land/bot_support_commander/bot_support_commander.json",
      },
      {
        name: "Security",
        character: "!LOC:Gold",
        color: [
          [70, 70, 70],
          [192, 192, 192],
        ],
        isCluster: true,
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.34,
          percent_open_bot: 0.34,
          percent_open_air: 0,
          percent_open_naval: 0.32,
          percent_open_orbital: 0,
          percent_land: 1,
          percent_air: 0,
          percent_naval: 0,
          percent_orbital: 0,
          metal_drain_check: 0.54,
          energy_drain_check: 0.77,
          metal_demand_check: 0.85,
          energy_demand_check: 0.92,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1.3,
          personality_tags: ["Default", "GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 0.5,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 3,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 3,
          max_basic_fabbers: 5,
          min_advanced_fabbers: 2,
          max_advanced_fabbers: 5,
        },
        commander:
          "/pa/units/land/bot_support_commander/bot_support_commander.json",
      },
      {
        name: "Security",
        character: "!LOC:Defender",
        color: [
          [70, 70, 70],
          [192, 192, 192],
        ],
        isCluster: true,
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.47,
          percent_open_bot: 0.26,
          percent_open_air: 0.21,
          percent_open_naval: 0.06,
          percent_open_orbital: 0,
          percent_vehicle: 0.45,
          percent_bot: 0.25,
          percent_air: 0.2,
          percent_naval: 0.05,
          percent_orbital: 0.05,
          metal_drain_check: 0.71,
          energy_drain_check: 0.8,
          metal_demand_check: 0.54,
          energy_demand_check: 0.65,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["Default", "GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 4,
          max_basic_fabbers: 5,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 5,
        },
        commander:
          "/pa/units/land/bot_support_commander/bot_support_commander.json",
      },
      {
        name: "Security",
        character: "!LOC:Luddite",
        color: [
          [70, 70, 70],
          [192, 192, 192],
        ],
        isCluster: true,
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.75,
          percent_open_bot: 0.25,
          percent_open_air: 0,
          percent_open_naval: 0,
          percent_open_orbital: 0,
          percent_vehicle: 0.75,
          percent_bot: 0.25,
          percent_air: 0,
          percent_naval: 0,
          percent_orbital: 0,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["Default", "GWAlly", "SlowerExpansion"],
          adv_eco_mod: 3,
          adv_eco_mod_alone: 3,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 5,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 5,
        },
        commander:
          "/pa/units/land/bot_support_commander/bot_support_commander.json",
      },
      {
        name: "Security",
        character: "!LOC:Technologist",
        color: [
          [70, 70, 70],
          [192, 192, 192],
        ],
        isCluster: true,
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.75,
          percent_open_bot: 0.25,
          percent_open_air: 0,
          percent_open_naval: 0,
          percent_open_orbital: 0,
          percent_vehicle: 0.75,
          percent_bot: 0.25,
          percent_air: 0,
          percent_naval: 0,
          percent_orbital: 0,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["Default", "GWAlly", "SlowerExpansion"],
          adv_eco_mod: 0.5,
          adv_eco_mod_alone: 0.5,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 3,
          fabber_to_factory_ratio_advanced: 2,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 4,
          max_basic_fabbers: 5,
          min_advanced_fabbers: 1,
          max_advanced_fabbers: 5,
        },
        commander:
          "/pa/units/land/bot_support_commander/bot_support_commander.json",
      },
      {
        name: "Security",
        character: "!LOC:Cautious",
        color: [
          [70, 70, 70],
          [192, 192, 192],
        ],
        isCluster: true,
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.75,
          percent_open_bot: 0.25,
          percent_open_air: 0,
          percent_open_naval: 0,
          percent_open_orbital: 0,
          percent_vehicle: 0.75,
          percent_bot: 0.25,
          percent_air: 0,
          percent_naval: 0,
          percent_orbital: 0,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 0.75,
          personality_tags: ["Default", "GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.3,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 4,
          max_basic_fabbers: 5,
          min_advanced_fabbers: 2,
          max_advanced_fabbers: 5,
        },
        commander:
          "/pa/units/land/bot_support_commander/bot_support_commander.json",
      },
      {
        name: "Security",
        character: "!LOC:Aggressive",
        color: [
          [70, 70, 70],
          [192, 192, 192],
        ],
        isCluster: true,
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.75,
          percent_open_bot: 0.25,
          percent_open_air: 0,
          percent_open_naval: 0,
          percent_open_orbital: 0,
          percent_vehicle: 0.75,
          percent_bot: 0.25,
          percent_air: 0,
          percent_naval: 0,
          percent_orbital: 0,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 2,
          personality_tags: ["Default", "GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.3,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 5,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 5,
        },
        commander:
          "/pa/units/land/bot_support_commander/bot_support_commander.json",
      },
      {
        name: "Security",
        character: "!LOC:Rush",
        color: [
          [70, 70, 70],
          [192, 192, 192],
        ],
        isCluster: true,
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0,
          percent_open_bot: 1,
          percent_open_air: 0,
          percent_open_naval: 0,
          percent_open_orbital: 0,
          percent_bot: 1,
          percent_vehicle: 0,
          percent_air: 0,
          percent_naval: 0,
          percent_orbital: 0,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1.5,
          personality_tags: ["Default", "GWAlly", "SlowerExpansion"],
          adv_eco_mod: 2,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 5,
          min_advanced_fabbers: 1,
          max_advanced_fabbers: 5,
        },
        commander:
          "/pa/units/land/bot_support_commander/bot_support_commander.json",
      },
      {
        name: "Security",
        character: "!LOC:Turtle",
        color: [
          [70, 70, 70],
          [192, 192, 192],
        ],
        isCluster: true,
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.9,
          percent_open_bot: 0.1,
          percent_open_air: 0,
          percent_open_naval: 0,
          percent_open_orbital: 0,
          percent_land: 1,
          percent_air: 0,
          percent_naval: 0,
          percent_orbital: 0,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 0.5,
          personality_tags: ["Default", "GWAlly", "SlowerExpansion"],
          adv_eco_mod: 0.5,
          adv_eco_mod_alone: 0.5,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 2,
          fabber_to_factory_ratio_advanced: 2,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 4,
          max_basic_fabbers: 5,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 5,
        },
        commander:
          "/pa/units/land/bot_support_commander/bot_support_commander.json",
      },
      {
        name: "Security",
        character: "!LOC:Original",
        color: [
          [70, 70, 70],
          [192, 192, 192],
        ],
        isCluster: true,
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.27,
          percent_open_bot: 0.27,
          percent_open_air: 0.46,
          percent_open_naval: 0,
          percent_open_orbital: 0,
          percent_land: 0.4,
          percent_air: 0.35,
          percent_naval: 0.2,
          percent_orbital: 0.05,
          metal_drain_check: 0.75,
          energy_drain_check: 0.85,
          metal_demand_check: 0.75,
          energy_demand_check: 0.85,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["Default", "GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.3,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 5,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 5,
        },
        commander:
          "/pa/units/land/bot_support_commander/bot_support_commander.json",
      },
      {
        name: "Security",
        character: "!LOC:Absurd",
        color: [
          [70, 70, 70],
          [192, 192, 192],
        ],
        isCluster: true,
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.47,
          percent_open_bot: 0.26,
          percent_open_air: 0.21,
          percent_open_naval: 0.06,
          percent_open_orbital: 0,
          percent_vehicle: 0.45,
          percent_bot: 0.25,
          percent_air: 0.2,
          percent_naval: 0.05,
          percent_orbital: 0.05,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["Default", "GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.3,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 5,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 5,
        },
        commander:
          "/pa/units/land/bot_support_commander/bot_support_commander.json",
      },
      {
        name: "Security",
        character: "!LOC:Relentless",
        color: [
          [70, 70, 70],
          [192, 192, 192],
        ],
        isCluster: true,
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.47,
          percent_open_bot: 0.26,
          percent_open_air: 0.21,
          percent_open_naval: 0.06,
          percent_open_orbital: 0,
          percent_vehicle: 0.45,
          percent_bot: 0.25,
          percent_air: 0.2,
          percent_naval: 0.05,
          percent_orbital: 0.05,
          metal_drain_check: 0.44,
          energy_drain_check: 0.55,
          metal_demand_check: 0.61,
          energy_demand_check: 0.7,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1.2,
          personality_tags: ["Default", "GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.2,
          adv_eco_mod_alone: 0.95,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 5,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 5,
        },
        commander:
          "/pa/units/land/bot_support_commander/bot_support_commander.json",
      },
      {
        name: "Security",
        character: "!LOC:Swarm",
        color: [
          [70, 70, 70],
          [192, 192, 192],
        ],
        isCluster: true,
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.47,
          percent_open_bot: 0.26,
          percent_open_air: 0.21,
          percent_open_naval: 0.06,
          percent_open_orbital: 0,
          percent_vehicle: 0.45,
          percent_bot: 0.25,
          percent_air: 0.2,
          percent_naval: 0.05,
          percent_orbital: 0.05,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.99,
          energy_demand_check: 0.99,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["Default", "GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.3,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 3,
          max_basic_fabbers: 5,
          min_advanced_fabbers: 1,
          max_advanced_fabbers: 5,
        },
        commander:
          "/pa/units/land/bot_support_commander/bot_support_commander.json",
      },
      {
        name: "Security",
        character: "!LOC:Economist",
        color: [
          [70, 70, 70],
          [192, 192, 192],
        ],
        isCluster: true,
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.47,
          percent_open_bot: 0.26,
          percent_open_air: 0.21,
          percent_open_naval: 0.06,
          percent_open_orbital: 0,
          percent_vehicle: 0.45,
          percent_bot: 0.25,
          percent_air: 0.2,
          percent_naval: 0.05,
          percent_orbital: 0.05,
          metal_drain_check: 0.71,
          energy_drain_check: 0.8,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["Default", "GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 4,
          max_basic_fabbers: 5,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 5,
        },
        commander:
          "/pa/units/land/bot_support_commander/bot_support_commander.json",
      },
    ], // minions
  };
});
