define(["coui://ui/mods/com.pa.quitch.gwaioverhaul/shared/units.js"], function (
  gwaioUnits
) {
  return {
    commanderUnits: [gwaioUnits.commander],
    commanderWeapons: [gwaioUnits.commanderSecondary],
    commanderAmmo: [
      gwaioUnits.commanderSecondaryAmmo,
      gwaioUnits.commanderAAAmmo,
      gwaioUnits.commanderAmmo,
      gwaioUnits.commanderTorpedoAmmo,
    ],
    commanderBuildArms: [gwaioUnits.commanderBuildArm],

    legonisUnitsNotMobile: [
      gwaioUnits.vehicleFactoryAdvanced,
      gwaioUnits.vehicleFactory,
    ],
    legonisUnitsMobile: [
      gwaioUnits.spinner,
      gwaioUnits.stryker,
      gwaioUnits.vehicleFabberAdvanced,
      gwaioUnits.vehicleFabber,
      gwaioUnits.skitter,
      gwaioUnits.inferno,
      gwaioUnits.storm,
      gwaioUnits.vanguard,
      gwaioUnits.sheller,
      gwaioUnits.drifter,
      gwaioUnits.leveler,
      gwaioUnits.ant,
      gwaioUnits.manhattan,
      gwaioUnits.ares,
    ],
    legonisWeapons: [],
    legonisAmmo: [
      gwaioUnits.spinnerAmmo,
      gwaioUnits.skitterAmmo,
      gwaioUnits.infernoAmmo,
      gwaioUnits.stormAmmo,
      gwaioUnits.vanguardAmmo,
      gwaioUnits.drifterAmmo,
      gwaioUnits.levelerAmmo,
      gwaioUnits.antAmmo,
      gwaioUnits.aresAmmo,
      gwaioUnits.aresSecondaryAmmo,
      gwaioUnits.aresStompAmmo,
    ],
    legonisBuildArms: [
      gwaioUnits.vehicleFabberAdvancedBuildArm,
      gwaioUnits.vehicleFabberBuildArm,
      gwaioUnits.vehicleFactoryAdvancedBuildArm,
      gwaioUnits.vehicleFactoryBuildArm,
    ],

    foundationUnitsNotMobile: [
      gwaioUnits.airFactoryAdvanced,
      gwaioUnits.airFactory,
      gwaioUnits.navalFactoryAdvanced,
      gwaioUnits.navalFactory,
    ],
    foundationUnitsMobileAir: [
      gwaioUnits.firefly,
      gwaioUnits.hornet,
      gwaioUnits.wyrm,
      gwaioUnits.bumblebee,
      gwaioUnits.airFabberAdvanced,
      gwaioUnits.airFabber,
      gwaioUnits.phoenix,
      gwaioUnits.hummingbird,
      gwaioUnits.kestrel,
      gwaioUnits.icarus,
      gwaioUnits.horsefly,
      gwaioUnits.angel,
      gwaioUnits.zeus,
      gwaioUnits.pelican,
      gwaioUnits.squall,
    ],
    foundationUnitsMobileNotAir: [
      gwaioUnits.barracuda,
      gwaioUnits.leviathan,
      gwaioUnits.orca,
      gwaioUnits.typhoon,
      gwaioUnits.barnacle,
      gwaioUnits.navalFabberAdvanced,
      gwaioUnits.navalFabber,
      gwaioUnits.narwhal,
      gwaioUnits.kaiju,
      gwaioUnits.stingray,
      gwaioUnits.kraken,
      gwaioUnits.piranha,
    ],
    foundationWeapons: [
      gwaioUnits.hornetWeapon,
      gwaioUnits.wyrmWeapon,
      gwaioUnits.bumblebeeWeapon,
      gwaioUnits.icarusWeapon,
      gwaioUnits.zeusWeapon,
      gwaioUnits.typhoonWeapon,
    ],
    foundationAmmo: [
      gwaioUnits.fireflyAmmo,
      gwaioUnits.hornetAmmo,
      gwaioUnits.wyrmAmmo,
      gwaioUnits.bumblebeeAmmo,
      gwaioUnits.phoenixAmmo,
      gwaioUnits.hummingbirdAmmo,
      gwaioUnits.kestrelAmmo,
      gwaioUnits.icarusAmmo,
      gwaioUnits.horseflyAmmo,
      gwaioUnits.zeusAmmo,
      gwaioUnits.barracudaAmmo,
      gwaioUnits.leviathanAmmo,
      gwaioUnits.orcaAmmo,
      gwaioUnits.orcaTorpedoAmmo,
      gwaioUnits.squallTorpedoAmmo,
      gwaioUnits.squallAmmo,
      gwaioUnits.narwhalAAAmmo,
      gwaioUnits.narwhalAmmo,
      gwaioUnits.narwhalTorpedoAmmo,
      gwaioUnits.kaijuSecondaryAmmo,
      gwaioUnits.kaijuAmmo,
      gwaioUnits.stingrayAAAmmo,
      gwaioUnits.stingrayAmmo,
      gwaioUnits.krakenMissileAmmo,
      gwaioUnits.krakenWeaponAmmo,
      gwaioUnits.piranhaAmmo,
    ],
    foundationBuildArms: [
      gwaioUnits.navalFactoryAdvancedBuildArm,
      gwaioUnits.navalFactoryBuildArm,
      gwaioUnits.airFabberAdvancedBuildArm,
      gwaioUnits.airFabberBuildArm,
      gwaioUnits.angelBuildArm,
      gwaioUnits.barnacleBuildArm,
      gwaioUnits.navalFabberAdvancedBuildArm,
      gwaioUnits.navalFabberBuildArm,
      gwaioUnits.navalFactoryAdvancedBuildArm,
      gwaioUnits.navalFactoryBuildArm,
    ],

    synchronousUnitsNotMobile: [
      gwaioUnits.botFactoryAdvanced,
      gwaioUnits.botFactory,
    ],
    synchronousUnitsMobile: [
      gwaioUnits.slammer,
      gwaioUnits.dox,
      gwaioUnits.stinger,
      gwaioUnits.boom,
      gwaioUnits.grenadier,
      gwaioUnits.locusts,
      gwaioUnits.gilE,
      gwaioUnits.colonel,
      gwaioUnits.bluehawk,
      gwaioUnits.spark,
      gwaioUnits.botFabberAdvanced,
      gwaioUnits.mend,
      gwaioUnits.stitch,
      gwaioUnits.botFabber,
      gwaioUnits.atlas,
    ],
    synchronousWeapons: [gwaioUnits.lobWeapon, gwaioUnits.sparkWeapon],
    synchronousAmmo: [
      gwaioUnits.slammerAmmo,
      gwaioUnits.doxAmmo,
      gwaioUnits.stingerWeapon,
      gwaioUnits.boomAmmo,
      gwaioUnits.locustsAmmo,
      gwaioUnits.gilEAmmo,
      gwaioUnits.colonelAmmo,
      gwaioUnits.bluehawkAmmo,
      gwaioUnits.sparkAmmo,
      gwaioUnits.atlasAmmo,
    ],
    synchronousBuildArms: [
      gwaioUnits.botFactoryAdvancedBuildArm,
      gwaioUnits.botFactoryBuildArm,
      gwaioUnits.colonelBuildArm,
      gwaioUnits.botFabberAdvancedBuildArm,
      gwaioUnits.mendBuildArm,
      gwaioUnits.stitchBuildArm,
      gwaioUnits.botFabberBuildArm,
    ],

    revenantsUnitsNotMobile: [
      gwaioUnits.catalyst,
      gwaioUnits.nukeLauncherAmmo,
      gwaioUnits.nukeLauncher,
      gwaioUnits.unitCannon,
      gwaioUnits.deepSpaceOrbitalRadar,
      gwaioUnits.anchor,
      gwaioUnits.halley,
      gwaioUnits.umbrella,
      gwaioUnits.jig,
      gwaioUnits.orbitalFactory,
      gwaioUnits.orbitalLauncher,
    ],
    revenantsUnitsMobile: [
      gwaioUnits.omega,
      gwaioUnits.orbitalFabber,
      gwaioUnits.avenger,
      gwaioUnits.astraeus,
      gwaioUnits.sxx,
      gwaioUnits.hermes,
      gwaioUnits.artemis,
      gwaioUnits.radarSatelliteAdvanced,
      gwaioUnits.arkyd,
      gwaioUnits.solarArray,
      gwaioUnits.helios,
    ],
    revenantsWeapons: [
      gwaioUnits.sxxWeapon,
      gwaioUnits.artemisWeapon,
      gwaioUnits.heliosWeaponAG,
    ],
    revenantsAmmo: [
      gwaioUnits.anchorAmmoAG,
      gwaioUnits.anchorAmmoAO,
      gwaioUnits.omegaAmmoAG,
      gwaioUnits.avengerAmmo,
      gwaioUnits.sxxAmmo,
      gwaioUnits.artemisAmmo,
    ],
    revenantsBuildArms: [
      gwaioUnits.nukeLauncherBuildArm,
      gwaioUnits.orbitalFabberBuildArm,
      gwaioUnits.orbitalFactoryBuildArm,
      gwaioUnits.orbitalLauncherBuildArm,
    ],

    clusterCommanders: [gwaioUnits.angel, gwaioUnits.colonel],
    clusterCommanderAmmo: [gwaioUnits.colonelAmmo],
    clusterUnits: [
      gwaioUnits.airFactoryAdvanced,
      gwaioUnits.airFactory,
      gwaioUnits.flak,
      gwaioUnits.galata,
      gwaioUnits.antiNukeLauncherAmmo,
      gwaioUnits.antiNukeLauncher,
      gwaioUnits.holkins,
      gwaioUnits.pelter,
      gwaioUnits.lob,
      gwaioUnits.botFactoryAdvanced,
      gwaioUnits.botFactory,
      gwaioUnits.catalyst,
      gwaioUnits.energyPlantAdvanced,
      gwaioUnits.energyPlant,
      gwaioUnits.energyStorage,
      gwaioUnits.wall,
      gwaioUnits.landMine,
      gwaioUnits.laserDefenseTowerAdvanced,
      gwaioUnits.singleLaserDefenseTower,
      gwaioUnits.laserDefenseTower,
      gwaioUnits.metalExtractorAdvanced,
      gwaioUnits.metalExtractor,
      gwaioUnits.metalStorage,
      gwaioUnits.nukeLauncherAmmo,
      gwaioUnits.nukeLauncher,
      gwaioUnits.radarAdvanced,
      gwaioUnits.radar,
      gwaioUnits.catapult,
      gwaioUnits.teleporter,
      gwaioUnits.ragnarok,
      gwaioUnits.vehicleFactoryAdvanced,
      gwaioUnits.vehicleFactory,
      gwaioUnits.navalFactoryAdvanced,
      gwaioUnits.navalFactory,
      gwaioUnits.torpedoLauncherAdvanced,
      gwaioUnits.torpedoLauncher,
    ],
    clusterWeapons: [
      gwaioUnits.holkinsWeapon,
      gwaioUnits.pelterWeapon,
      gwaioUnits.lob,
      gwaioUnits.ragnarokWeapon,
    ],
    clusterAmmo: [
      gwaioUnits.landMineAmmo,
      gwaioUnits.flakAmmo,
      gwaioUnits.galataAmmo,
      gwaioUnits.antiNukeLauncherAmmo,
      gwaioUnits.holkinsAmmo,
      gwaioUnits.pelterAmmo,
      gwaioUnits.laserDefenseTowerAdvancedAmmo,
      gwaioUnits.singleLaserDefenseTowerAmmo,
      gwaioUnits.laserDefenseTowerAmmo,
      gwaioUnits.nukeLauncherAmmo,
      gwaioUnits.catapultAmmo,
      gwaioUnits.anchorAmmoAG,
      gwaioUnits.anchorAmmoAO,
      gwaioUnits.umbrellaAmmo,
      gwaioUnits.torpedoLauncherAdvancedLandAmmo,
      gwaioUnits.torpedoLauncherAdvancedWaterAmmo,
      gwaioUnits.torpedoLauncherAdvancedAmmo,
      gwaioUnits.torpedoLauncherLandAmmo,
      gwaioUnits.torpedoLauncherWaterAmmo,
      gwaioUnits.torpedoLauncherAmmo,
    ],
    clusterBuildArms: [
      gwaioUnits.antiNukeLauncherBuildArm,
      gwaioUnits.botFactoryAdvancedBuildArm,
      gwaioUnits.botFactoryAdvancedBuildArm,
      gwaioUnits.botFactoryBuildArm,
      gwaioUnits.botFactoryBuildArm,
      gwaioUnits.nukeLauncherBuildArm,
      gwaioUnits.unitCannonBuildArm,
      gwaioUnits.vehicleFactoryAdvancedBuildArm,
      gwaioUnits.vehicleFactoryBuildArm,
      gwaioUnits.navalFactoryAdvancedBuildArm,
      gwaioUnits.navalFactoryBuildArm,
    ],
  };
});
