define(["coui://ui/mods/com.pa.quitch.gwaioverhaul/shared/units.js"], function (
  gwoUnit
) {
  return {
    commanderUnits: [gwoUnit.commander],
    commanderWeapons: [gwoUnit.commanderSecondary],
    commanderAmmo: [
      gwoUnit.commanderSecondaryAmmo,
      gwoUnit.commanderAAAmmo,
      gwoUnit.commanderAmmo,
      gwoUnit.commanderTorpedoAmmo,
    ],
    commanderBuildArms: [gwoUnit.commanderBuildArm],

    legonisUnitsNotMobile: [
      gwoUnit.vehicleFactoryAdvanced,
      gwoUnit.vehicleFactory,
    ],
    legonisUnitsMobile: [
      gwoUnit.spinner,
      gwoUnit.stryker,
      gwoUnit.vehicleFabberAdvanced,
      gwoUnit.vehicleFabber,
      gwoUnit.skitter,
      gwoUnit.inferno,
      gwoUnit.storm,
      gwoUnit.vanguard,
      gwoUnit.sheller,
      gwoUnit.drifter,
      gwoUnit.leveler,
      gwoUnit.ant,
      gwoUnit.manhattan,
      gwoUnit.ares,
    ],
    legonisWeapons: [],
    legonisAmmo: [
      gwoUnit.spinnerAmmo,
      gwoUnit.skitterAmmo,
      gwoUnit.infernoAmmo,
      gwoUnit.stormAmmo,
      gwoUnit.vanguardAmmo,
      gwoUnit.drifterAmmo,
      gwoUnit.levelerAmmo,
      gwoUnit.antAmmo,
      gwoUnit.aresAmmo,
      gwoUnit.aresSecondaryAmmo,
      gwoUnit.aresStompAmmo,
    ],
    legonisBuildArms: [
      gwoUnit.vehicleFabberAdvancedBuildArm,
      gwoUnit.vehicleFabberBuildArm,
      gwoUnit.vehicleFactoryAdvancedBuildArm,
      gwoUnit.vehicleFactoryBuildArm,
    ],

    foundationUnitsNotMobile: [
      gwoUnit.airFactoryAdvanced,
      gwoUnit.airFactory,
      gwoUnit.navalFactoryAdvanced,
      gwoUnit.navalFactory,
    ],
    foundationUnitsMobileAir: [
      gwoUnit.firefly,
      gwoUnit.hornet,
      gwoUnit.wyrm,
      gwoUnit.bumblebee,
      gwoUnit.airFabberAdvanced,
      gwoUnit.airFabber,
      gwoUnit.phoenix,
      gwoUnit.hummingbird,
      gwoUnit.kestrel,
      gwoUnit.icarus,
      gwoUnit.horsefly,
      gwoUnit.angel,
      gwoUnit.zeus,
      gwoUnit.pelican,
      gwoUnit.squall,
    ],
    foundationUnitsMobileNotAir: [
      gwoUnit.barracuda,
      gwoUnit.leviathan,
      gwoUnit.orca,
      gwoUnit.typhoon,
      gwoUnit.barnacle,
      gwoUnit.navalFabberAdvanced,
      gwoUnit.navalFabber,
      gwoUnit.narwhal,
      gwoUnit.kaiju,
      gwoUnit.stingray,
      gwoUnit.kraken,
      gwoUnit.piranha,
    ],
    foundationWeapons: [
      gwoUnit.hornetWeapon,
      gwoUnit.wyrmWeapon,
      gwoUnit.bumblebeeWeapon,
      gwoUnit.icarusWeapon,
      gwoUnit.zeusWeapon,
      gwoUnit.typhoonWeapon,
    ],
    foundationAmmo: [
      gwoUnit.fireflyAmmo,
      gwoUnit.hornetAmmo,
      gwoUnit.wyrmAmmo,
      gwoUnit.bumblebeeAmmo,
      gwoUnit.phoenixAmmo,
      gwoUnit.hummingbirdAmmo,
      gwoUnit.kestrelAmmo,
      gwoUnit.icarusAmmo,
      gwoUnit.horseflyAmmo,
      gwoUnit.zeusAmmo,
      gwoUnit.barracudaAmmo,
      gwoUnit.leviathanAmmo,
      gwoUnit.orcaAmmo,
      gwoUnit.orcaTorpedoAmmo,
      gwoUnit.squallTorpedoAmmo,
      gwoUnit.squallAmmo,
      gwoUnit.narwhalAAAmmo,
      gwoUnit.narwhalAmmo,
      gwoUnit.narwhalTorpedoAmmo,
      gwoUnit.kaijuSecondaryAmmo,
      gwoUnit.kaijuAmmo,
      gwoUnit.stingrayAAAmmo,
      gwoUnit.stingrayAmmo,
      gwoUnit.krakenMissileAmmo,
      gwoUnit.krakenWeaponAmmo,
      gwoUnit.piranhaAmmo,
    ],
    foundationBuildArms: [
      gwoUnit.navalFactoryAdvancedBuildArm,
      gwoUnit.navalFactoryBuildArm,
      gwoUnit.airFabberAdvancedBuildArm,
      gwoUnit.airFabberBuildArm,
      gwoUnit.angelBuildArm,
      gwoUnit.barnacleBuildArm,
      gwoUnit.navalFabberAdvancedBuildArm,
      gwoUnit.navalFabberBuildArm,
      gwoUnit.navalFactoryAdvancedBuildArm,
      gwoUnit.navalFactoryBuildArm,
    ],

    synchronousUnitsNotMobile: [gwoUnit.botFactoryAdvanced, gwoUnit.botFactory],
    synchronousUnitsMobile: [
      gwoUnit.slammer,
      gwoUnit.dox,
      gwoUnit.stinger,
      gwoUnit.boom,
      gwoUnit.grenadier,
      gwoUnit.locusts,
      gwoUnit.gilE,
      gwoUnit.colonel,
      gwoUnit.bluehawk,
      gwoUnit.spark,
      gwoUnit.botFabberAdvanced,
      gwoUnit.mend,
      gwoUnit.stitch,
      gwoUnit.botFabber,
      gwoUnit.atlas,
    ],
    synchronousWeapons: [gwoUnit.lobWeapon, gwoUnit.sparkWeapon],
    synchronousAmmo: [
      gwoUnit.slammerAmmo,
      gwoUnit.doxAmmo,
      gwoUnit.stingerWeapon,
      gwoUnit.boomAmmo,
      gwoUnit.locustsAmmo,
      gwoUnit.gilEAmmo,
      gwoUnit.colonelAmmo,
      gwoUnit.bluehawkAmmo,
      gwoUnit.sparkAmmo,
      gwoUnit.atlasAmmo,
    ],
    synchronousBuildArms: [
      gwoUnit.botFactoryAdvancedBuildArm,
      gwoUnit.botFactoryBuildArm,
      gwoUnit.colonelBuildArm,
      gwoUnit.botFabberAdvancedBuildArm,
      gwoUnit.mendBuildArm,
      gwoUnit.stitchBuildArm,
      gwoUnit.botFabberBuildArm,
    ],

    revenantsUnitsNotMobile: [
      gwoUnit.catalyst,
      gwoUnit.nukeLauncherAmmo,
      gwoUnit.nukeLauncher,
      gwoUnit.unitCannon,
      gwoUnit.deepSpaceOrbitalRadar,
      gwoUnit.anchor,
      gwoUnit.halley,
      gwoUnit.umbrella,
      gwoUnit.jig,
      gwoUnit.orbitalFactory,
      gwoUnit.orbitalLauncher,
    ],
    revenantsUnitsMobile: [
      gwoUnit.omega,
      gwoUnit.orbitalFabber,
      gwoUnit.avenger,
      gwoUnit.astraeus,
      gwoUnit.sxx,
      gwoUnit.hermes,
      gwoUnit.artemis,
      gwoUnit.radarSatelliteAdvanced,
      gwoUnit.arkyd,
      gwoUnit.solarArray,
      gwoUnit.helios,
    ],
    revenantsWeapons: [gwoUnit.sxxWeapon, gwoUnit.artemisWeapon],
    revenantsAmmo: [
      gwoUnit.anchorAmmoAG,
      gwoUnit.anchorAmmoAO,
      gwoUnit.omegaAmmoAG,
      gwoUnit.avengerAmmo,
      gwoUnit.sxxAmmo,
      gwoUnit.artemisAmmo,
    ],
    revenantsBuildArms: [
      gwoUnit.nukeLauncherBuildArm,
      gwoUnit.orbitalFabberBuildArm,
      gwoUnit.orbitalFactoryBuildArm,
      gwoUnit.orbitalLauncherBuildArm,
    ],

    clusterCommanders: [gwoUnit.angel, gwoUnit.colonel],
    clusterCommanderAmmo: [gwoUnit.colonelAmmo],
    clusterUnits: [
      gwoUnit.airFactoryAdvanced,
      gwoUnit.airFactory,
      gwoUnit.flak,
      gwoUnit.galata,
      gwoUnit.antiNukeLauncherAmmo,
      gwoUnit.antiNukeLauncher,
      gwoUnit.holkins,
      gwoUnit.pelter,
      gwoUnit.lob,
      gwoUnit.botFactoryAdvanced,
      gwoUnit.botFactory,
      gwoUnit.catalyst,
      gwoUnit.energyPlantAdvanced,
      gwoUnit.energyPlant,
      gwoUnit.energyStorage,
      gwoUnit.wall,
      gwoUnit.landMine,
      gwoUnit.laserDefenseTowerAdvanced,
      gwoUnit.singleLaserDefenseTower,
      gwoUnit.laserDefenseTower,
      gwoUnit.metalExtractorAdvanced,
      gwoUnit.metalExtractor,
      gwoUnit.metalStorage,
      gwoUnit.nukeLauncherAmmo,
      gwoUnit.nukeLauncher,
      gwoUnit.radarAdvanced,
      gwoUnit.radar,
      gwoUnit.catapult,
      gwoUnit.teleporter,
      gwoUnit.ragnarok,
      gwoUnit.vehicleFactoryAdvanced,
      gwoUnit.vehicleFactory,
      gwoUnit.navalFactoryAdvanced,
      gwoUnit.navalFactory,
      gwoUnit.torpedoLauncherAdvanced,
      gwoUnit.torpedoLauncher,
    ],
    clusterWeapons: [
      gwoUnit.holkinsWeapon,
      gwoUnit.pelterWeapon,
      gwoUnit.lob,
      gwoUnit.ragnarokWeapon,
    ],
    clusterAmmo: [
      gwoUnit.landMineAmmo,
      gwoUnit.flakAmmo,
      gwoUnit.galataAmmo,
      gwoUnit.antiNukeLauncherAmmo,
      gwoUnit.holkinsAmmo,
      gwoUnit.pelterAmmo,
      gwoUnit.laserDefenseTowerAdvancedAmmo,
      gwoUnit.singleLaserDefenseTowerAmmo,
      gwoUnit.laserDefenseTowerAmmo,
      gwoUnit.nukeLauncherAmmo,
      gwoUnit.catapultAmmo,
      gwoUnit.anchorAmmoAG,
      gwoUnit.anchorAmmoAO,
      gwoUnit.umbrellaAmmo,
      gwoUnit.torpedoLauncherAdvancedLandAmmo,
      gwoUnit.torpedoLauncherAdvancedWaterAmmo,
      gwoUnit.torpedoLauncherAdvancedAmmo,
      gwoUnit.torpedoLauncherLandAmmo,
      gwoUnit.torpedoLauncherWaterAmmo,
      gwoUnit.torpedoLauncherAmmo,
    ],
    clusterBuildArms: [
      gwoUnit.antiNukeLauncherBuildArm,
      gwoUnit.botFactoryAdvancedBuildArm,
      gwoUnit.botFactoryAdvancedBuildArm,
      gwoUnit.botFactoryBuildArm,
      gwoUnit.botFactoryBuildArm,
      gwoUnit.nukeLauncherBuildArm,
      gwoUnit.unitCannonBuildArm,
      gwoUnit.vehicleFactoryAdvancedBuildArm,
      gwoUnit.vehicleFactoryBuildArm,
      gwoUnit.navalFactoryAdvancedBuildArm,
      gwoUnit.navalFactoryBuildArm,
    ],
  };
});
