define(["coui://ui/mods/com.pa.quitch.gwaioverhaul/shared/units.js"], function (
  gwoUnit
) {
  return {
    units: [
      { name: "!LOC:Advanced Air Factory", path: gwoUnit.airFactoryAdvanced },
      { name: "!LOC:Air Factory", path: gwoUnit.airFactory },
      { name: "Firefly", path: gwoUnit.firefly },
      { name: "Hornet", path: gwoUnit.hornet },
      { name: "Wyrm", path: gwoUnit.wyrm },
      { name: "Bumblebee", path: gwoUnit.bumblebee },
      { name: "!LOC:Advanced Fab Aircraft", path: gwoUnit.airFabberAdvanced },
      { name: "!LOC:Fabrication Aircraft", path: gwoUnit.airFabber },
      { name: "Phoenix", path: gwoUnit.phoenix },
      { name: "Hummingbird", path: gwoUnit.hummingbird },
      { name: "Kestrel", path: gwoUnit.kestrel },
      { name: "Icarus", path: gwoUnit.icarus },
      { name: "Horsefly", path: gwoUnit.horsefly },
      { name: "Angel", path: gwoUnit.angel },
      { name: "Zeus", path: gwoUnit.zeus },
      { name: "Pelican", path: gwoUnit.pelican },
      { name: "!LOC:Commander", path: gwoUnit.commander },
      { name: "Spinner", path: gwoUnit.spinner },
      { name: "Flak Cannon", path: gwoUnit.flak },
      { name: "Galata Turret", path: gwoUnit.galata },
      { name: "!LOC:Anti-Nuke Launcher", path: gwoUnit.antiNukeLauncher },
      { name: "Holkins", path: gwoUnit.holkins },
      { name: "Pelter", path: gwoUnit.pelter },
      { name: "Lob", path: gwoUnit.lob },
      { name: "Slammer", path: gwoUnit.slammer },
      { name: "Dox", path: gwoUnit.dox },
      { name: "Stryker", path: gwoUnit.stryker },
      { name: "Stinger", path: gwoUnit.stinger },
      { name: "Boom", path: gwoUnit.boom },
      { name: "!LOC:Advanced Bot Factory", path: gwoUnit.botFactoryAdvanced },
      { name: "!LOC:Bot Factory", path: gwoUnit.botFactory },
      { name: "Grenadier", path: gwoUnit.grenadier },
      { name: "Locusts", path: gwoUnit.locusts },
      { name: "Gil-E", path: gwoUnit.gilE },
      { name: "Colonel", path: gwoUnit.colonel },
      { name: "Bluehawk", path: gwoUnit.bluehawk },
      { name: "Spark", path: gwoUnit.spark },
      { name: "Catalyst", path: gwoUnit.catalyst },
      { name: "!LOC:Advanced Energy Plant", path: gwoUnit.energyPlantAdvanced },
      { name: "!LOC:Energy Plant", path: gwoUnit.energyPlant },
      { name: "!LOC:Energy Storage", path: gwoUnit.energyStorage },
      {
        name: "!LOC:Advanced Fabrication Bot",
        path: gwoUnit.botFabberAdvanced,
      },
      { name: "!LOC:Fabrication Bot", path: gwoUnit.botFabber },
      { name: "Mend", path: gwoUnit.mend },
      { name: "Stitch", path: gwoUnit.stitch },
      {
        name: "!LOC:Advanced Fabrication Vehicle",
        path: gwoUnit.vehicleFabberAdvanced,
      },
      { name: "!LOC:Fabrication Vehicle", path: gwoUnit.vehicleFabber },
      { name: "!LOC:Wall", path: gwoUnit.wall },
      { name: "!LOC:Land Mine", path: gwoUnit.landMine },
      { name: "Skitter", path: gwoUnit.skitter },
      {
        name: "!LOC:Advanced Laser Defense Tower",
        path: gwoUnit.laserDefenseTowerAdvanced,
      },
      {
        name: "!LOC:Single Laser Defense Tower",
        path: gwoUnit.singleLaserDefenseTower,
      },
      { name: "!LOC:Laser Defense Tower", path: gwoUnit.laserDefenseTower },
      {
        name: "!LOC:Advanced Metal Extractor",
        path: gwoUnit.metalExtractorAdvanced,
      },
      { name: "!LOC:Metal Extractor", path: gwoUnit.metalExtractor },
      { name: "!LOC:Metal Storage", path: gwoUnit.metalStorage },
      { name: "!LOC:Nuclear Missile Launcher", path: gwoUnit.nukeLauncher },
      { name: "!LOC:Advanced Radar", path: gwoUnit.radarAdvanced },
      { name: "!LOC:Radar", path: gwoUnit.radar },
      { name: "Catapult", path: gwoUnit.catapult },
      { name: "Inferno", path: gwoUnit.inferno },
      { name: "Storm", path: gwoUnit.storm },
      { name: "Vanguard", path: gwoUnit.vanguard },
      { name: "Sheller", path: gwoUnit.sheller },
      { name: "Drifter", path: gwoUnit.drifter },
      { name: "Leveler", path: gwoUnit.leveler },
      { name: "Ant", path: gwoUnit.ant },
      { name: "Manhattan", path: gwoUnit.manhattan },
      { name: "!LOC:Teleporter", path: gwoUnit.teleporter },
      { name: "Atlas", path: gwoUnit.atlas },
      { name: "Ragnarok", path: gwoUnit.ragnarok },
      { name: "Ares", path: gwoUnit.ares },
      { name: "Unit Cannon", path: gwoUnit.unitCannon },
      { name: "!LOC:Vehicle Factory", path: gwoUnit.vehicleFactory },
      {
        name: "!LOC:Advanced Vehicle Factory",
        path: gwoUnit.vehicleFactoryAdvanced,
      },
      { name: "!LOC:Planetary Radar", path: gwoUnit.deepSpaceOrbitalRadar },
      { name: "Anchor", path: gwoUnit.anchor },
      { name: "Halley", path: gwoUnit.halley },
      { name: "Umbrella", path: gwoUnit.umbrella },
      { name: "Jig", path: gwoUnit.jig },
      { name: "Omega", path: gwoUnit.omega },
      { name: "!LOC:Orbital Fabrication Bot", path: gwoUnit.orbitalFabber },
      { name: "!LOC:Orbital Factory", path: gwoUnit.orbitalFactory },
      { name: "Avenger", path: gwoUnit.avenger },
      { name: "Astraeus", path: gwoUnit.astraeus },
      { name: "!LOC:SXX-1304 Laser Platform", path: gwoUnit.sxx },
      { name: "!LOC:Orbital Launcher", path: gwoUnit.orbitalLauncher },
      { name: "Hermes", path: gwoUnit.hermes },
      { name: "Artemis", path: gwoUnit.artemis },
      {
        name: "!LOC:Advanced Radar Satellite",
        path: gwoUnit.radarSatelliteAdvanced,
      },
      { name: "ARKYD", path: gwoUnit.arkyd },
      { name: "!LOC:Solar Array", path: gwoUnit.solarArray },
      { name: "Helios", path: gwoUnit.helios },
      { name: "Barracuda", path: gwoUnit.barracuda },
      { name: "Leviathan", path: gwoUnit.leviathan },
      { name: "Orca", path: gwoUnit.orca },
      { name: "Typhoon", path: gwoUnit.typhoon },
      { name: "Squall", path: gwoUnit.squall },
      { name: "Barnacle", path: gwoUnit.barnacle },
      {
        name: "!LOC:Advanced Fabrication Ship",
        path: gwoUnit.navalFabberAdvanced,
      },
      { name: "!LOC:Fabrication Ship", path: gwoUnit.navalFabber },
      { name: "Narwhal", path: gwoUnit.narwhal },
      { name: "Kaiju", path: gwoUnit.kaiju },
      { name: "Stingray", path: gwoUnit.stingray },
      {
        name: "!LOC:Advanced Naval Factory",
        path: gwoUnit.navalFactoryAdvanced,
      },
      { name: "!LOC:Naval Factory", path: gwoUnit.navalFactory },
      { name: "Kraken", path: gwoUnit.kraken },
      { name: "Piranha", path: gwoUnit.piranha },
      {
        name: "!LOC:Advanced Torpedo Launcher",
        path: gwoUnit.torpedoLauncherAdvanced,
      },
      { name: "!LOC:Torpedo Launcher", path: gwoUnit.torpedoLauncher },
      { name: "!LOC:Radar Jamming Station", path: gwoUnit.radarJammingStation },
      { name: "!LOC:Nyx", path: gwoUnit.nyx },
      { name: "!LOC:Ward", path: gwoUnit.ward },
      { name: "!LOC:Kessler", path: gwoUnit.kessler },
    ],
  };
});
