// General game balance variables

define([
], function(
) {

    return {
        initialCardSlots: 4,

        numberOfSystems: [
                18, // Small
                24, // Medium
                36, // Large
                54, // Uber
                78 // Rediq
        ],

        // New ramping feature so that the galaxy size.
        galaxySizeDiffMod: [
            1.25,
            1.2,
            1.15,
            1.1,
            1.0
        ],

        difficultyInfo: [
            {
                rampDifficulty: true,
                adv_eco_mod: 3,
                adv_eco_mod_alone: 3,
                goForKill: false,
                microType: 0,
                neuralDataMod: 5,
                mandatoryMinions: 0,
                minionMod: 0,
                bossDemandCheckMod: 1.75,
                priority_scout_metal_spots: false,
                useEasierSystemTemplate: true,
                factory_build_delay_min: 180,
                factory_build_delay_max: 240,
                unable_to_expand_delay: 1200,
                enable_commander_danger_responses: false,
                per_expansion_delay: 1200,
                fabber_to_factory_ratio_basic: 10,
                fabber_to_factory_ratio_advanced: 5,
                fabber_alone_on_planet_mod: 1,
                basic_to_advanced_factory_ratio: 0,
                factory_alone_on_planet_mod: 1,
                min_basic_fabbers: 10,
                max_basic_fabbers: 10,
                min_advanced_fabbers: 3,
                max_advanced_fabbers: 10,
                personality_tags:
                [
                    "SlowerExpansion"
                ],
                econBase: 0.4,
                econRatePerDist: 0.005,
                metalDrainCheck: 0.14,
                metalDrainCheckPerDist: 0.003,
                metalDemandCheck: 0.21,
                metalDemandCheckPerDist: 0.004,
                energyDrainCheck: 0.25,
                energyDrainCheckPerDist: 0.003,
                energyDemandCheck: 0.3,
                energyDemandCheckPerDist: 0.004
            },
            {
                rampDifficulty: true,
                adv_eco_mod: 2,
                adv_eco_mod_alone: 2,
                goForKill: false,
                microType: 0,
                neuralDataMod: 2,
                mandatoryMinions: 0,
                minionMod: 0.25,
                bossDemandCheckMod: 1.25,
                priority_scout_metal_spots: false,
                useEasierSystemTemplate: false,
                factory_build_delay_min: 0,
                factory_build_delay_max: 0,
                unable_to_expand_delay: 0,
                enable_commander_danger_responses: false,
                per_expansion_delay: 120,
                fabber_to_factory_ratio_basic: 5,
                fabber_to_factory_ratio_advanced: 5,
                fabber_alone_on_planet_mod: 1,
                basic_to_advanced_factory_ratio: 0,
                factory_alone_on_planet_mod: 1,
                min_basic_fabbers: 5,
                max_basic_fabbers: 20,
                min_advanced_fabbers: 3,
                max_advanced_fabbers: 20,
                econBase: 0.55,
                econRatePerDist: 0.01,
                metalDrainCheck: 0.54,
                metalDemandCheck: 0.77,
                energyDrainCheck: 0.95,
                energyDemandCheck: 0.92,
            },
            {
                rampDifficulty: true,
                adv_eco_mod: 1.5,
                adv_eco_mod_alone: 1.5,
                goForKill: false,
                microType: 1,
                neuralDataMod: 1,
                mandatoryMinions: 0,
                minionMod: 0.5,
                bossDemandCheckMod: 1,
                priority_scout_metal_spots: true,
                useEasierSystemTemplate: false,
                factory_build_delay_min: 0,
                factory_build_delay_max: 0,
                unable_to_expand_delay: 0,
                enable_commander_danger_responses: true,
                per_expansion_delay: 0,
                fabber_to_factory_ratio_basic: 2,
                fabber_to_factory_ratio_advanced: 1,
                fabber_alone_on_planet_mod: 1,
                basic_to_advanced_factory_ratio: 0,
                factory_alone_on_planet_mod: 1,
                min_basic_fabbers: 4,
                max_basic_fabbers: 30,
                min_advanced_fabbers: 3,
                max_advanced_fabbers: 30,
                econBase: 0.7,
                econRatePerDist: 0.01,
                metalDrainCheck: 0.54,
                metalDemandCheck: 0.77,
                energyDrainCheck: 0.95,
                energyDemandCheck: 0.92,
            },
            {
                rampDifficulty: true,
                adv_eco_mod: 1.25,
                adv_eco_mod_alone: 1.25,
                goForKill: true,
                microType: 2,
                neuralDataMod: 1,
                mandatoryMinions: 0,
                minionMod: 0.75,
                bossDemandCheckMod: 1,
                priority_scout_metal_spots: true,
                useEasierSystemTemplate: false,
                factory_build_delay_min: 0,
                factory_build_delay_max: 0,
                unable_to_expand_delay: 0,
                enable_commander_danger_responses: true,
                per_expansion_delay: 0,
                fabber_to_factory_ratio_basic: 1,
                fabber_to_factory_ratio_advanced: 1,
                fabber_alone_on_planet_mod: 2,
                basic_to_advanced_factory_ratio: 0,
                factory_alone_on_planet_mod: 0.5,
                min_basic_fabbers: 3,
                max_basic_fabbers: 40,
                min_advanced_fabbers: 2,
                max_advanced_fabbers: 40,
                personality_tags:
                [
                    "PreventsWaste"
                ],
                econBase: 0.85,
                econRatePerDist: 0.01,
                metalDrainCheck: 0.54,
                metalDemandCheck: 0.77,
                energyDrainCheck: 0.95,
                energyDemandCheck: 0.92,
            },
            {
                rampDifficulty: true,
                adv_eco_mod: 1.1,
                adv_eco_mod_alone: 0.95,
                goForKill: true,
                microType: 2,
                neuralDataMod: 1,
                mandatoryMinions: 0,
                minionMod: 1,
                bossDemandCheckMod: 1,
                priority_scout_metal_spots: true,
                useEasierSystemTemplate: false,
                factory_build_delay_min: 0,
                factory_build_delay_max: 0,
                unable_to_expand_delay: 0,
                enable_commander_danger_responses: true,
                per_expansion_delay: 0,
                fabber_to_factory_ratio_basic: 1,
                fabber_to_factory_ratio_advanced: 3,
                fabber_alone_on_planet_mod: 3,
                basic_to_advanced_factory_ratio: 0,
                factory_alone_on_planet_mod: 0.5,
                min_basic_fabbers: 2,
                max_basic_fabbers: 50,
                min_advanced_fabbers: 2,
                max_advanced_fabbers: 50,
                personality_tags:
                [
                    "PreventsWaste"
                ],
                econBase: 1,
                econRatePerDist: 0.01,
                metalDrainCheck: 0.54,
                metalDemandCheck: 0.77,
                energyDrainCheck: 0.95,
                energyDemandCheck: 0.92,
            },
            {
                rampDifficulty: true,
                adv_eco_mod: 1,
                adv_eco_mod_alone: 0.85,
                goForKill: true,
                microType: 2,
                neuralDataMod: 1,
                mandatoryMinions: 1,
                minionMod: 1,
                bossDemandCheckMod: 1,
                priority_scout_metal_spots: true,
                useEasierSystemTemplate: false,
                factory_build_delay_min: 0,
                factory_build_delay_max: 0,
                unable_to_expand_delay: 0,
                enable_commander_danger_responses: true,
                per_expansion_delay: 0,
                fabber_to_factory_ratio_basic: 1,
                fabber_to_factory_ratio_advanced: 2,
                fabber_alone_on_planet_mod: 3,
                basic_to_advanced_factory_ratio: 0,
                factory_alone_on_planet_mod: 0.5,
                min_basic_fabbers: 3,
                max_basic_fabbers: 100,
                min_advanced_fabbers: 1,
                max_advanced_fabbers: 100,
                personality_tags:
                [
                    "PreventsWaste"
                ],
                econBase: 1,
                econRatePerDist: 0.05,
                metalDrainCheck: 0.54,
                metalDemandCheck: 0.57,
                energyDrainCheck: 0.85,
                energyDemandCheck: 0.82,
            }
        ],

        workerMetalDrainCheck: [0.75, 0.6],
        workerEnergyDrainCheck: [0.85, 0.7],
        workerMetalDemandCheck: [0.9, 0.75],
        workerEnergyDemandCheck: [1.00, 0.85],
    };
});
