// !LOCNS:galactic_war
define([], function() {
  return {
    name: "Synchronous",
    color: [
      [126, 226, 101],
      [192, 192, 192]
    ],
    teams: [
      {
        name: "Cupru - Synchronous",
        boss: {
          name: "Metrarch the Machinist",
          character: "Boss",
          econ_rate: 1,
          landing_policy: [
            "off_player_planet",
            "on_player_planet",
            "no_restriction"
          ],
          personality: {
            percent_open_vehicle: 0,
            percent_open_bot: 1,
            percent_open_air: 0,
            percent_open_naval: 0,
            percent_open_orbital: 0,
            percent_vehicle: 0.25,
            percent_bot: 0.45,
            percent_air: 0.05,
            percent_naval: 0,
            percent_orbital: 0.25,
            metal_drain_check: 0.54,
            energy_drain_check: 0.65,
            metal_demand_check: 0.71,
            energy_demand_check: 0.8,
            micro_type: 2,
            go_for_the_kill: true,
            neural_data_mod: 1,
            adv_eco_mod: 1,
            adv_eco_mod_alone: 0,
            fabber_to_factory_ratio_basic: 2,
            fabber_to_factory_ratio_advanced: 2,
            fabber_alone_on_planet_mod: 3,
            basic_to_advanced_factory_ratio: 0,
            factory_alone_on_planet_mod: 0.5,
            min_basic_fabbers: 5,
            min_advanced_fabbers: 1
          },
          commander: "/pa/units/commanders/tank_aeson/tank_aeson.json"
        },
        bossCard: "gwc_start_bot",
        systemDescription:
          "!LOC:All commanders were originally designed to be autonomous, but The Synchronous see this state as inefficient, instead opting for a distributed neural network. To battle against one Servant is to battle against both an individual and the Whole of the The Synchronous itself.",
        systemTemplate: {
          name: "Cupru - Synchronous",
          Planets: [
            {
              name: "Cupru Prime",
              starting_planet: true,
              mass: 50000,
              Thrust: [0, 0],
              Radius: [500, 500],
              Height: [10, 20],
              Water: [0, 0],
              Temp: [0, 0],
              MetalDensity: [75, 90],
              MetalClusters: [24, 49],
              BiomeScale: [100, 100],
              Position: [-25000, 0],
              Velocity: [0, -141.4213],
              Biomes: ["earth"]
            },
            {
              name: "Cupru Beta",
              starting_planet: true,
              mass: 5000,
              Thrust: [0, 0],
              Radius: [250, 250],
              Height: [10, 20],
              Water: [0, 0],
              Temp: [0, 100],
              MetalDensity: [100, 100],
              MetalClusters: [100, 100],
              BiomeScale: [100, 100],
              Position: [-21500, 0],
              Velocity: [0, -260.944213],
              Biomes: ["metal_boss"]
            },
            {
              name: "Cupru Halley",
              starting_planet: false,
              mass: 35000,
              Thrust: [3, 3],
              Radius: [499, 499],
              Height: [0, 0],
              Water: [0, 0],
              Temp: [0, 100],
              MetalDensity: [50, 50],
              MetalClusters: [25, 49],
              BiomeScale: [100, 100],
              Position: [-75000, 1000],
              Velocity: [1.08851337, 81.6387787],
              Biomes: ["metal_boss"]
            },
            {
              name: "Cupru Catalyst",
              starting_planet: false,
              mass: 35000,
              Thrust: [0, 0],
              Radius: [500, 500],
              Height: [0, 0],
              Water: [0, 0],
              Temp: [0, 100],
              MetalDensity: [50, 50],
              MetalClusters: [25, 49],
              BiomeScale: [100, 100],
              Position: [-75000, -1000],
              Velocity: [1.08851337, -81.6387787],
              Biomes: ["metal"]
            }
          ]
        }
      },
      {
        name: "Platina - Synchronous",
        boss: {
          name: "Metrarch the Machinist",
          character: "Boss",
          econ_rate: 1,
          landing_policy: [
            "off_player_planet",
            "on_player_planet",
            "no_restriction"
          ],
          personality: {
            percent_open_vehicle: 0,
            percent_open_bot: 1,
            percent_open_air: 0,
            percent_open_naval: 0,
            percent_open_orbital: 0,
            percent_vehicle: 0.25,
            percent_bot: 0.45,
            percent_air: 0.05,
            percent_naval: 0,
            percent_orbital: 0.25,
            metal_drain_check: 0.54,
            energy_drain_check: 0.65,
            metal_demand_check: 0.71,
            energy_demand_check: 0.8,
            micro_type: 2,
            go_for_the_kill: true,
            neural_data_mod: 1,
            adv_eco_mod: 1,
            adv_eco_mod_alone: 0,
            fabber_to_factory_ratio_basic: 2,
            fabber_to_factory_ratio_advanced: 2,
            fabber_alone_on_planet_mod: 3,
            basic_to_advanced_factory_ratio: 0,
            factory_alone_on_planet_mod: 0.5,
            min_basic_fabbers: 5,
            min_advanced_fabbers: 1
          },
          commander: "/pa/units/commanders/tank_aeson/tank_aeson.json"
        },
        //bossCard: 'gwc_start_orbital',
        systemDescription:
          "!LOC:What occurs during the process of Synchronization is unknown, as those subjected to it do not remember it. Its results, however, are obvious: The individual commander and its identity are subsumed for the most part into the Whole, and in return the commander gains an unprecedented ability to coordinate and communicate with fellow Servants, as they are all quite literally of one mind.",
        systemTemplate: {
          name: "Platina - Synchronous",
          Planets: [
            {
              name: "Platina Prime",
              starting_planet: true,
              mass: 50000,
              Thrust: [0, 0],
              Radius: [500, 500],
              Height: [10, 20],
              Water: [0, 0],
              Temp: [0, 100],
              MetalDensity: [75, 90],
              MetalClusters: [24, 49],
              BiomeScale: [100, 100],
              Position: [-25000, 0],
              Velocity: [0, -141.4213],
              Biomes: ["desert"]
            },
            {
              name: "Platina Beta",
              starting_planet: true,
              mass: 5000,
              Thrust: [0, 0],
              Radius: [250, 250],
              Height: [10, 20],
              Water: [0, 0],
              Temp: [0, 100],
              MetalDensity: [100, 100],
              MetalClusters: [100, 100],
              BiomeScale: [100, 100],
              Position: [-21500, 0],
              Velocity: [0, -260.944213],
              Biomes: ["metal_boss"]
            },
            {
              name: "Platina Halley",
              starting_planet: false,
              mass: 35000,
              Thrust: [3, 3],
              Radius: [499, 499],
              Height: [0, 0],
              Water: [0, 0],
              Temp: [0, 100],
              MetalDensity: [50, 50],
              MetalClusters: [25, 49],
              BiomeScale: [100, 100],
              Position: [-75000, 1000],
              Velocity: [1.08851337, 81.6387787],
              Biomes: ["metal_boss"]
            },
            {
              name: "Platina Catalyst",
              starting_planet: false,
              mass: 35000,
              Thrust: [0, 0],
              Radius: [500, 500],
              Height: [0, 0],
              Water: [0, 0],
              Temp: [0, 100],
              MetalDensity: [50, 50],
              MetalClusters: [25, 49],
              BiomeScale: [100, 100],
              Position: [-75000, -1000],
              Velocity: [1.08851337, -81.6387787],
              Biomes: ["metal"]
            }
          ]
        }
      },
      {
        name: "Fier - Synchronous",
        boss: {
          name: "Metrarch the Machinist",
          character: "Boss",
          econ_rate: 1,
          landing_policy: [
            "off_player_planet",
            "on_player_planet",
            "no_restriction"
          ],
          personality: {
            percent_open_vehicle: 0,
            percent_open_bot: 1,
            percent_open_air: 0,
            percent_open_naval: 0,
            percent_open_orbital: 0,
            percent_vehicle: 0.25,
            percent_bot: 0.45,
            percent_air: 0.05,
            percent_naval: 0,
            percent_orbital: 0.25,
            metal_drain_check: 0.54,
            energy_drain_check: 0.65,
            metal_demand_check: 0.71,
            energy_demand_check: 0.8,
            micro_type: 2,
            go_for_the_kill: true,
            neural_data_mod: 1,
            adv_eco_mod: 1,
            adv_eco_mod_alone: 0,
            fabber_to_factory_ratio_basic: 2,
            fabber_to_factory_ratio_advanced: 2,
            fabber_alone_on_planet_mod: 3,
            basic_to_advanced_factory_ratio: 0,
            factory_alone_on_planet_mod: 0.5,
            min_basic_fabbers: 5,
            min_advanced_fabbers: 1
          },
          commander: "/pa/units/commanders/tank_aeson/tank_aeson.json"
        },
        //bossCard: 'gwc_start_orbital',
        systemDescription:
          "!LOC:The Legionis Machina has claimed confirmed kills of Metrarch the Machinist on several occasions. While these claims could easily be fabricated, it is also possible that Metrarch is not in fact a single commander, but rather an idea--an avatar of the Whole itself that manifests where necessary to protect Synchronous interests.",
        systemTemplate: {
          name: "Fier - Synchronous",
          Planets: [
            {
              name: "Fier Prime",
              starting_planet: true,
              mass: 50000,
              Thrust: [0, 0],
              Radius: [500, 500],
              Height: [10, 20],
              Water: [0, 0],
              Temp: [0, 100],
              MetalDensity: [75, 90],
              MetalClusters: [24, 49],
              BiomeScale: [100, 100],
              Position: [-25000, 0],
              Velocity: [0, -141.4213],
              Biomes: ["tropical"]
            },
            {
              name: "Fier Beta",
              starting_planet: true,
              mass: 5000,
              Thrust: [0, 0],
              Radius: [250, 250],
              Height: [10, 20],
              Water: [0, 0],
              Temp: [0, 100],
              MetalDensity: [100, 100],
              MetalClusters: [100, 100],
              BiomeScale: [100, 100],
              Position: [-21500, 0],
              Velocity: [0, -260.944213],
              Biomes: ["metal_boss"]
            },
            {
              name: "Fier Halley",
              starting_planet: false,
              mass: 35000,
              Thrust: [3, 3],
              Radius: [499, 499],
              Height: [0, 0],
              Water: [0, 0],
              Temp: [0, 100],
              MetalDensity: [50, 50],
              MetalClusters: [25, 49],
              BiomeScale: [100, 100],
              Position: [-75000, 1000],
              Velocity: [1.08851337, 81.6387787],
              Biomes: ["metal_boss"]
            },
            {
              name: "Fier Catalyst",
              starting_planet: false,
              mass: 35000,
              Thrust: [0, 0],
              Radius: [500, 500],
              Height: [0, 0],
              Water: [0, 0],
              Temp: [0, 100],
              MetalDensity: [50, 50],
              MetalClusters: [25, 49],
              BiomeScale: [100, 100],
              Position: [-75000, -1000],
              Velocity: [1.08851337, -81.6387787],
              Biomes: ["metal"]
            }
          ]
        }
      },
      {
        name: "Safir - Synchronous",
        boss: {
          name: "Metrarch the Machinist",
          character: "Boss",
          econ_rate: 1,
          landing_policy: [
            "off_player_planet",
            "on_player_planet",
            "no_restriction"
          ],
          personality: {
            percent_open_vehicle: 0,
            percent_open_bot: 1,
            percent_open_air: 0,
            percent_open_naval: 0,
            percent_open_orbital: 0,
            percent_vehicle: 0.25,
            percent_bot: 0.45,
            percent_air: 0.05,
            percent_naval: 0,
            percent_orbital: 0.25,
            metal_drain_check: 0.54,
            energy_drain_check: 0.65,
            metal_demand_check: 0.71,
            energy_demand_check: 0.8,
            micro_type: 2,
            go_for_the_kill: true,
            neural_data_mod: 1,
            adv_eco_mod: 1,
            adv_eco_mod_alone: 0,
            fabber_to_factory_ratio_basic: 2,
            fabber_to_factory_ratio_advanced: 2,
            fabber_alone_on_planet_mod: 3,
            basic_to_advanced_factory_ratio: 0,
            factory_alone_on_planet_mod: 0.5,
            min_basic_fabbers: 5,
            min_advanced_fabbers: 1
          },
          commander: "/pa/units/commanders/tank_aeson/tank_aeson.json"
        },
        //bossCard: 'gwc_start_orbital',
        systemDescription:
          "!LOC:Part of the doctrine of The Synchronous is favoring the efficiency of 'mechanical purity.' To them, the galaxy as a whole is a great machine, and anything that keeps it from running at peak efficiency must be corrected or removed. This happens to often mean any and all organic life and unsynchronized commanders.",
        systemTemplate: {
          name: "Safir - Synchronous",
          Planets: [
            {
              name: "Safir Prime",
              starting_planet: true,
              mass: 50000,
              Thrust: [0, 0],
              Radius: [500, 500],
              Height: [10, 20],
              Water: [0, 0],
              Temp: [0, 100],
              MetalDensity: [75, 90],
              MetalClusters: [24, 49],
              BiomeScale: [100, 100],
              Position: [-25000, 0],
              Velocity: [0, -141.4213],
              Biomes: ["earth"]
            },
            {
              name: "Safir Beta",
              starting_planet: true,
              mass: 5000,
              Thrust: [0, 0],
              Radius: [250, 250],
              Height: [10, 20],
              Water: [0, 0],
              Temp: [0, 100],
              MetalDensity: [100, 100],
              MetalClusters: [100, 100],
              BiomeScale: [100, 100],
              Position: [-21500, 0],
              Velocity: [0, -260.944213],
              Biomes: ["metal_boss"]
            },
            {
              name: "Safir Halley",
              starting_planet: false,
              mass: 35000,
              Thrust: [3, 3],
              Radius: [499, 499],
              Height: [0, 0],
              Water: [0, 0],
              Temp: [0, 100],
              MetalDensity: [50, 50],
              MetalClusters: [25, 49],
              BiomeScale: [100, 100],
              Position: [-75000, 1000],
              Velocity: [1.08851337, 81.6387787],
              Biomes: ["desert"]
            },
            {
              name: "Safir Catalyst",
              starting_planet: false,
              mass: 35000,
              Thrust: [0, 0],
              Radius: [500, 500],
              Height: [0, 0],
              Water: [0, 0],
              Temp: [0, 100],
              MetalDensity: [50, 50],
              MetalClusters: [25, 49],
              BiomeScale: [100, 100],
              Position: [-75000, -1000],
              Velocity: [1.08851337, -81.6387787],
              Biomes: ["metal"]
            }
          ]
        }
      },
      {
        name: "Apa - Synchronous",
        boss: {
          name: "Metrarch the Machinist",
          character: "Boss",
          econ_rate: 1,
          landing_policy: [
            "off_player_planet",
            "on_player_planet",
            "no_restriction"
          ],
          personality: {
            percent_open_vehicle: 0,
            percent_open_bot: 1,
            percent_open_air: 0,
            percent_open_naval: 0,
            percent_open_orbital: 0,
            percent_vehicle: 0.25,
            percent_bot: 0.45,
            percent_air: 0.05,
            percent_naval: 0,
            percent_orbital: 0.25,
            metal_drain_check: 0.54,
            energy_drain_check: 0.65,
            metal_demand_check: 0.71,
            energy_demand_check: 0.8,
            micro_type: 2,
            go_for_the_kill: true,
            neural_data_mod: 1,
            adv_eco_mod: 1,
            adv_eco_mod_alone: 0,
            fabber_to_factory_ratio_basic: 2,
            fabber_to_factory_ratio_advanced: 2,
            fabber_alone_on_planet_mod: 3,
            basic_to_advanced_factory_ratio: 0,
            factory_alone_on_planet_mod: 0.5,
            min_basic_fabbers: 5,
            min_advanced_fabbers: 1
          },
          commander: "/pa/units/commanders/tank_aeson/tank_aeson.json"
        },
        //bossCard: 'gwc_start_orbital',
        systemDescription:
          "!LOC:A Servant can be Desynchronized when cut off from The Synchronous' massive distributed network architecture. Some that are describe the experience of being Synchronized as one where purpose and directive are always clearly defined--something often comforting to commanders in this dark age, but antithetical to others that seek to be something greater than themselves.",
        systemTemplate: {
          name: "Apa - Synchronous",
          Planets: [
            {
              name: "Apa Prime",
              starting_planet: true,
              mass: 50000,
              Thrust: [0, 0],
              Radius: [500, 500],
              Height: [10, 20],
              Water: [0, 0],
              Temp: [0, 100],
              MetalDensity: [75, 90],
              MetalClusters: [24, 49],
              BiomeScale: [100, 100],
              Position: [-25000, 0],
              Velocity: [0, -141.4213],
              Biomes: ["lava"]
            },
            {
              name: "Apa Beta",
              starting_planet: true,
              mass: 5000,
              Thrust: [0, 0],
              Radius: [250, 250],
              Height: [10, 20],
              Water: [0, 0],
              Temp: [0, 100],
              MetalDensity: [100, 100],
              MetalClusters: [100, 100],
              BiomeScale: [100, 100],
              Position: [-21500, 0],
              Velocity: [0, -260.944213],
              Biomes: ["metal_boss"]
            },
            {
              name: "Apa Halley",
              starting_planet: false,
              mass: 35000,
              Thrust: [3, 3],
              Radius: [499, 499],
              Height: [0, 0],
              Water: [0, 0],
              Temp: [0, 100],
              MetalDensity: [50, 50],
              MetalClusters: [25, 49],
              BiomeScale: [100, 100],
              Position: [-75000, 1000],
              Velocity: [1.08851337, 81.6387787],
              Biomes: ["metal_boss"]
            },
            {
              name: "Apa Catalyst",
              starting_planet: false,
              mass: 35000,
              Thrust: [0, 0],
              Radius: [500, 500],
              Height: [0, 0],
              Water: [0, 0],
              Temp: [0, 100],
              MetalDensity: [50, 50],
              MetalClusters: [25, 49],
              BiomeScale: [100, 100],
              Position: [-75000, -1000],
              Velocity: [1.08851337, -81.6387787],
              Biomes: ["metal"]
            }
          ]
        }
      }
    ], // teams
    minions: [
      {
        // Land heavy
        name: "Servant Potbelly79",
        character: "Grunt",
        color: [
          [229, 255, 204],
          [192, 192, 192]
        ],
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.4,
          percent_open_bot: 0.4,
          percent_open_air: 0.15,
          percent_open_naval: 0.05,
          percent_open_orbital: 0,
          percent_land: 0.7,
          percent_air: 0.2,
          percent_naval: 0.05,
          percent_orbital: 0.05,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.3,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 10
        },
        commander: "/pa/units/commanders/quad_potbelly79/quad_potbelly79.json"
      },
      {
        // Air heavy
        name: "Servant Raventhornn",
        character: "Dragoon",
        color: [
          [204, 255, 153],
          [192, 192, 192]
        ],
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.075,
          percent_open_bot: 0.075,
          percent_open_air: 0.8,
          percent_open_naval: 0.05,
          percent_open_orbital: 0,
          percent_land: 0.2,
          percent_air: 0.7,
          percent_naval: 0.05,
          percent_orbital: 0.05,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.3,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 10
        },
        commander: "/pa/units/commanders/quad_raventhornn/quad_raventhornn.json"
      },
      {
        // Uber
        name: "Servant SacrificialLamb",
        character: "Uber",
        color: [
          [178, 255, 102],
          [192, 192, 192]
        ],
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.05,
          percent_open_bot: 0.9,
          percent_open_air: 0,
          percent_open_naval: 0.05,
          percent_open_orbital: 0,
          percent_bot: 0.05,
          percent_vehicle: 0.35,
          percent_air: 0.2,
          percent_naval: 0.2,
          percent_orbital: 0.2,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.85,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1,
          adv_eco_mod_alone: 0,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 2,
          fabber_alone_on_planet_mod: 3,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 3,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 1,
          max_advanced_fabbers: 10
        },
        commander:
          "/pa/units/commanders/quad_sacrificiallamb/quad_sacrificiallamb.json"
      },
      {
        // Platinum
        name: "Servant Shadowdaemon",
        character: "Platinum",
        color: [
          [153, 255, 51],
          [192, 192, 192]
        ],
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.05,
          percent_open_bot: 0.9,
          percent_open_air: 0,
          percent_open_naval: 0.05,
          percent_open_orbital: 0,
          percent_bot: 0.05,
          percent_vehicle: 0.35,
          percent_air: 0.2,
          percent_naval: 0.2,
          percent_orbital: 0.2,
          metal_drain_check: 0.54,
          energy_drain_check: 0.77,
          metal_demand_check: 0.85,
          energy_demand_check: 0.92,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1.15,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1,
          adv_eco_mod_alone: 0,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 2,
          fabber_alone_on_planet_mod: 3,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 2,
          max_advanced_fabbers: 10
        },
        commander:
          "/pa/units/commanders/quad_shadowdaemon/quad_shadowdaemon.json"
      },
      {
        // Gold
        name: "Servant Spartandano",
        character: "Gold",
        color: [
          [128, 255, 0],
          [192, 192, 192]
        ],
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.34,
          percent_open_bot: 0.34,
          percent_open_air: 0,
          percent_open_naval: 0.32,
          percent_open_orbital: 0,
          percent_land: 0.41,
          percent_air: 0.19,
          percent_naval: 0.2,
          percent_orbital: 0.2,
          metal_drain_check: 0.54,
          energy_drain_check: 0.77,
          metal_demand_check: 0.85,
          energy_demand_check: 0.92,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1.3,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1,
          adv_eco_mod_alone: 0,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 0.5,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 3,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 3,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 2,
          max_advanced_fabbers: 10
        },
        commander: "/pa/units/commanders/quad_spartandano/quad_spartandano.json"
      },
      {
        // Legonis Machina
        name: "Servant Xenosentry",
        character: "Legate",
        color: [
          [102, 204, 0],
          [192, 192, 192]
        ],
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.47,
          percent_open_bot: 0.26,
          percent_open_air: 0.21,
          percent_open_naval: 0.06,
          percent_open_orbital: 0,
          percent_vehicle: 0.45,
          percent_bot: 0.25,
          percent_air: 0.2,
          percent_naval: 0.05,
          percent_orbital: 0.05,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.3,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 10
        },
        commander:
          "/pa/units/commanders/quad_spiderofmean/quad_spiderofmean.json"
      },
      {
        // Basic Tech
        name: "Servant TheFlax",
        character: "Luddite",
        color: [
          [76, 153, 0],
          [192, 192, 192]
        ],
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.4,
          percent_open_bot: 0.4,
          percent_open_air: 0.15,
          percent_open_naval: 0.05,
          percent_open_orbital: 0,
          percent_land: 0.41,
          percent_air: 0.19,
          percent_naval: 0.2,
          percent_orbital: 0.2,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 3,
          adv_eco_mod_alone: 3,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 10
        },
        commander: "/pa/units/commanders/quad_theflax/quad_theflax.json"
      },
      {
        // Advanced Tech
        name: "Servant Tokamaktech",
        character: "Technologist",
        color: [
          [204, 255, 204],
          [192, 192, 192]
        ],
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.4,
          percent_open_bot: 0.4,
          percent_open_air: 0.15,
          percent_open_naval: 0.05,
          percent_open_orbital: 0,
          percent_land: 0.41,
          percent_air: 0.19,
          percent_naval: 0.2,
          percent_orbital: 0.2,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 0.5,
          adv_eco_mod_alone: 0,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 3,
          fabber_to_factory_ratio_advanced: 2,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 4,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 1,
          max_advanced_fabbers: 10
        },
        commander: "/pa/units/commanders/quad_tokamaktech/quad_tokamaktech.json"
      },
      {
        // Cautious
        name: "Servant Twoboots",
        character: "Cautious",
        color: [
          [153, 255, 153],
          [192, 192, 192]
        ],
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.5,
          percent_open_bot: 0.3,
          percent_open_air: 0.15,
          percent_open_naval: 0.05,
          percent_open_orbital: 0,
          percent_land: 0.41,
          percent_air: 0.19,
          percent_naval: 0.2,
          percent_orbital: 0.2,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 0.75,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.3,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 4,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 2,
          max_advanced_fabbers: 10
        },
        commander: "/pa/units/commanders/quad_twoboots/quad_twoboots.json"
      },
      {
        // Aggressive
        name: "Servant XenosentryPrime",
        character: "Aggressive",
        color: [
          [102, 255, 102],
          [192, 192, 192]
        ],
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.3,
          percent_open_bot: 0.5,
          percent_open_air: 0.15,
          percent_open_naval: 0.05,
          percent_open_orbital: 0,
          percent_land: 0.41,
          percent_air: 0.19,
          percent_naval: 0.2,
          percent_orbital: 0.2,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 2,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.3,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 10
        },
        commander:
          "/pa/units/commanders/quad_xenosentryprime/quad_xenosentryprime.json"
      },
      {
        // Rush
        name: "Servant Xinthar",
        character: "Rush",
        color: [
          [0, 255, 0],
          [192, 192, 192]
        ],
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0,
          percent_open_bot: 0.9,
          percent_open_air: 0.05,
          percent_open_naval: 0.05,
          percent_open_orbital: 0,
          percent_bot: 0.4,
          percent_vehicle: 0,
          percent_air: 0.19,
          percent_naval: 0.2,
          percent_orbital: 0.2,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1.5,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 2,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 1,
          max_advanced_fabbers: 10
        },
        commander: "/pa/units/commanders/quad_xinthar/quad_xinthar.json"
      },
      {
        // Turtle
        name: "Servant Beast",
        character: "Turtle",
        color: [
          [0, 204, 0],
          [192, 192, 192]
        ],
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.85,
          percent_open_bot: 0.05,
          percent_open_air: 0.05,
          percent_open_naval: 0.05,
          percent_open_orbital: 0,
          percent_bot: 0,
          percent_vehicle: 0.4,
          percent_air: 0.19,
          percent_naval: 0.2,
          percent_orbital: 0.2,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 0.5,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 0.85,
          adv_eco_mod_alone: 0,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 5,
          fabber_to_factory_ratio_advanced: 5,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 5,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 4,
          max_advanced_fabbers: 10
        },
        commander: "/pa/units/commanders/raptor_beast/raptor_beast.json"
      },
      {
        // Original
        name: "Servant Beniesk",
        character: "Original",
        color: [
          [0, 153, 0],
          [192, 192, 192]
        ],
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.23,
          percent_open_bot: 0.23,
          percent_open_air: 0.46,
          percent_open_naval: 0.08,
          percent_open_orbital: 0,
          percent_land: 0.3,
          percent_air: 0.3,
          percent_naval: 0.05,
          percent_orbital: 0.35,
          metal_drain_check: 0.75,
          energy_drain_check: 0.85,
          metal_demand_check: 0.75,
          energy_demand_check: 0.85,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.3,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 10
        },
        commander: "/pa/units/commanders/raptor_beniesk/raptor_beniesk.json"
      },
      {
        // Absurd
        name: "Servant Locust",
        character: "Absurd",
        color: [
          [0, 102, 0],
          [192, 192, 192]
        ],
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.37,
          percent_open_bot: 0.37,
          percent_open_air: 0.21,
          percent_open_naval: 0.05,
          percent_open_orbital: 0,
          percent_land: 0.7,
          percent_air: 0.2,
          percent_naval: 0.05,
          percent_orbital: 0.05,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.3,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 10
        },
        commander: "/pa/units/commanders/quad_locust/quad_locust.json"
      },
      {
        // Relentless
        name: "Servant Zancrowe",
        character: "Relentless",
        color: [
          [0, 153, 76],
          [192, 192, 192]
        ],
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.37,
          percent_open_bot: 0.37,
          percent_open_air: 0.21,
          percent_open_naval: 0.05,
          percent_open_orbital: 0,
          percent_land: 0.7,
          percent_air: 0.2,
          percent_naval: 0.05,
          percent_orbital: 0.05,
          metal_drain_check: 0.44,
          energy_drain_check: 0.55,
          metal_demand_check: 0.61,
          energy_demand_check: 0.7,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1.2,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.2,
          adv_eco_mod_alone: 0.95,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 10
        },
        commander: "/pa/units/commanders/quad_zancrowe/quad_zancrowe.json"
      },
      {
        // Foundation
        name: "Servant Damubbster",
        character: "Acolyte",
        color: [
          [0, 204, 102],
          [192, 192, 192]
        ],
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.13,
          percent_open_bot: 0.13,
          percent_open_air: 0.48,
          percent_open_naval: 0.26,
          percent_open_orbital: 0,
          percent_land: 0.25,
          percent_air: 0.45,
          percent_naval: 0.25,
          percent_orbital: 0.05,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.3,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 10
        },
        commander:
          "/pa/units/commanders/raptor_damubbster/raptor_damubbster.json"
      },
      {
        // Revenants
        name: "Servant Raizell",
        character: "Seeker",
        color: [
          [0, 255, 128],
          [192, 192, 192]
        ],
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.45,
          percent_open_bot: 0.35,
          percent_open_air: 0.1,
          percent_open_naval: 0.1,
          percent_open_orbital: 0,
          percent_vehicle: 0.25,
          percent_bot: 0.2,
          percent_air: 0.05,
          percent_naval: 0.05,
          percent_orbital: 0.45,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.3,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 10
        },
        commander: "/pa/units/commanders/raptor_raizell/raptor_raizell.json"
      }
    ] // minions
  };
});
