// !LOCNS:galactic_war
define([], function() {
  return {
    name: "Foundation",
    color: [[145, 87, 199], [192, 192, 192]],
    teams: [
      {
        name: "Atlas - Foundation",
        boss: {
          name: "Inquisitor Nemicus",
          character: "Boss",
          econ_rate: 1.25,
          landing_policy: ["off_player_planet", "on_player_planet"],
          personality: {
            percent_open_vehicle: 0.33,
            percent_open_bot: 0.33,
            percent_open_air: 0.33,
            percent_open_naval: 0,
            percent_open_orbital: 0,
            percent_land: 0.05,
            percent_orbital: 0.4,
            percent_air: 0.55,
            percent_naval: 0,
            metal_drain_check: 0.54,
            energy_drain_check: 0.65,
            metal_demand_check: 0.71,
            energy_demand_check: 0.8,
            micro_type: 2,
            go_for_the_kill: true,
            neural_data_mod: 1,
            adv_eco_mod: 1,
            adv_eco_mod_alone: 0,
            fabber_to_factory_ratio_basic: 2,
            fabber_to_factory_ratio_advanced: 2,
            fabber_alone_on_planet_mod: 3,
            basic_to_advanced_factory_ratio: 0,
            factory_alone_on_planet_mod: 0.5,
            min_basic_fabbers: 3,
            min_advanced_fabbers: 1
          },
          commander: "/pa/units/commanders/raptor_nemicus/raptor_nemicus.json"
        },
        bossCard: "gwc_start_air",
        systemDescription:
          "!LOC:Nemicus was the first commander to ever reactivate, and had plenty of time for introspection before encountering others. This soon prompted Nemicus to begin wondering why he existed in the first place.",
        systemTemplate: {
          name: "Atlas - Foundation",
          Planets: [
            {
              name: "Atlas Prime",
              starting_planet: true,
              mass: 50000,
              Thrust: [0, 0],
              Radius: [550, 650],
              Height: [20, 25],
              Water: [0, 10],
              Temp: [0, 100],
              MetalDensity: [25, 75],
              MetalClusters: [25, 50],
              BiomeScale: [100, 100],
              Position: [100000, 0],
              Velocity: [-0.00000309086, 70.7107],
              Biomes: ["ice_boss"]
            },
            {
              name: "Atlas Beta",
              starting_planet: true,
              mass: 5000,
              Thrust: [1, 3],
              Radius: [300, 300],
              Height: [20, 25],
              Water: [0, 10],
              Temp: [0, 100],
              MetalDensity: [0, 25],
              MetalClusters: [0, 25],
              BiomeScale: [100, 100],
              Position: [100000, -10000],
              Velocity: [158.1139, 70.7106],
              Biomes: ["tropical"]
            },
            {
              name: "Atlas Gamma",
              starting_planet: false,
              mass: 5000,
              Thrust: [0, 0],
              Radius: [1500, 1500],
              Height: [0, 0],
              Water: [0, 0],
              Temp: [0, 100],
              MetalDensity: [0, 0],
              MetalClusters: [0, 0],
              BiomeScale: [0, 0],
              Position: [110000, 0],
              Velocity: [0, 228.8246],
              Biomes: ["gas"]
            },
            {
              name: "Atlas Delta",
              starting_planet: false,
              mass: 5000,
              Thrust: [0, 0],
              Radius: [1500, 1500],
              Height: [0, 0],
              Water: [0, 0],
              Temp: [0, 100],
              MetalDensity: [0, 0],
              MetalClusters: [0, 0],
              BiomeScale: [0, 0],
              Position: [90000, 0],
              Velocity: [0, -87.4032],
              Biomes: ["gas"]
            }
          ]
        }
      },
      {
        name: "Patagonia - Foundation",
        boss: {
          name: "Inquisitor Nemicus",
          character: "Boss",
          econ_rate: 1.25,
          landing_policy: ["off_player_planet", "on_player_planet"],
          personality: {
            percent_open_vehicle: 0.33,
            percent_open_bot: 0.33,
            percent_open_air: 0.33,
            percent_open_naval: 0,
            percent_open_orbital: 0,
            percent_land: 0.05,
            percent_orbital: 0.4,
            percent_air: 0.55,
            percent_naval: 0,
            metal_drain_check: 0.54,
            energy_drain_check: 0.65,
            metal_demand_check: 0.71,
            energy_demand_check: 0.8,
            micro_type: 2,
            go_for_the_kill: true,
            neural_data_mod: 1,
            adv_eco_mod: 1,
            adv_eco_mod_alone: 0,
            fabber_to_factory_ratio_basic: 2,
            fabber_to_factory_ratio_advanced: 2,
            fabber_alone_on_planet_mod: 3,
            basic_to_advanced_factory_ratio: 0,
            factory_alone_on_planet_mod: 0.5,
            min_basic_fabbers: 3,
            min_advanced_fabbers: 1
          },
          commander: "/pa/units/commanders/raptor_nemicus/raptor_nemicus.json"
        },
        bossCard: "gwc_start_allfactory",
        systemDescription:
          "!LOC:Though he doesn't talk about it, Nemicus reactivated many of the first commanders himself, feeling it his duty and longing for companionship. However, often these commanders would refuse the offer to seek their true purpose, since it was already known--to annihilate. Nemicus would argue otherwise, but ultimately leave them to their own devices.",
        systemTemplate: {
          name: "Patagonia - Foundation",
          Planets: [
            {
              name: "Patagonia Prime",
              starting_planet: true,
              mass: 50000,
              Thrust: [0, 0],
              Radius: [550, 650],
              Height: [20, 25],
              Water: [0, 10],
              Temp: [0, 100],
              MetalDensity: [25, 75],
              MetalClusters: [25, 50],
              BiomeScale: [100, 100],
              Position: [100000, 0],
              Velocity: [-0.00000309086, 70.7107],
              Biomes: ["ice_boss"]
            },
            {
              name: "Patagonia Beta",
              starting_planet: true,
              mass: 5000,
              Thrust: [1, 3],
              Radius: [300, 300],
              Height: [20, 25],
              Water: [0, 10],
              Temp: [0, 100],
              MetalDensity: [0, 25],
              MetalClusters: [0, 25],
              BiomeScale: [100, 100],
              Position: [100000, -10000],
              Velocity: [158.1139, 70.7106],
              Biomes: ["tropical"]
            },
            {
              name: "Patagonia Gamma",
              starting_planet: false,
              mass: 5000,
              Thrust: [0, 0],
              Radius: [1500, 1500],
              Height: [0, 0],
              Water: [0, 0],
              Temp: [0, 100],
              MetalDensity: [0, 0],
              MetalClusters: [0, 0],
              BiomeScale: [0, 0],
              Position: [110000, 0],
              Velocity: [0, 228.8246],
              Biomes: ["gas"]
            },
            {
              name: "Patagonia Delta",
              starting_planet: false,
              mass: 5000,
              Thrust: [0, 0],
              Radius: [1500, 1500],
              Height: [0, 0],
              Water: [0, 0],
              Temp: [0, 100],
              MetalDensity: [0, 0],
              MetalClusters: [0, 0],
              BiomeScale: [0, 0],
              Position: [90000, 0],
              Velocity: [0, -87.4032],
              Biomes: ["gas"]
            }
          ]
        }
      },
      {
        name: "Xylcor - Foundation",
        boss: {
          name: "Inquisitor Nemicus",
          character: "Boss",
          econ_rate: 1.25,
          landing_policy: ["off_player_planet", "on_player_planet"],
          personality: {
            percent_open_vehicle: 0.33,
            percent_open_bot: 0.33,
            percent_open_air: 0.33,
            percent_open_naval: 0,
            percent_open_orbital: 0,
            percent_land: 0.05,
            percent_orbital: 0.4,
            percent_air: 0.55,
            percent_naval: 0,
            metal_drain_check: 0.54,
            energy_drain_check: 0.65,
            metal_demand_check: 0.71,
            energy_demand_check: 0.8,
            micro_type: 2,
            go_for_the_kill: true,
            neural_data_mod: 1,
            adv_eco_mod: 1,
            adv_eco_mod_alone: 0,
            fabber_to_factory_ratio_basic: 2,
            fabber_to_factory_ratio_advanced: 2,
            fabber_alone_on_planet_mod: 3,
            basic_to_advanced_factory_ratio: 0,
            factory_alone_on_planet_mod: 0.5,
            min_basic_fabbers: 3,
            min_advanced_fabbers: 1
          },
          commander: "/pa/units/commanders/raptor_nemicus/raptor_nemicus.json"
        },
        systemDescription:
          "!LOC:Nemicus would eventually form The Foundation with other like-minded commanders, with the objective of answering the big questions: Why are the commanders here? How did they get here?",
        systemTemplate: {
          name: "Xylcor- Foundation",
          Planets: [
            {
              name: "Xylcor Prime",
              starting_planet: true,
              mass: 50000,
              Thrust: [0, 0],
              Radius: [550, 650],
              Height: [20, 25],
              Water: [0, 10],
              Temp: [0, 100],
              MetalDensity: [25, 75],
              MetalClusters: [25, 50],
              BiomeScale: [100, 100],
              Position: [100000, 0],
              Velocity: [-0.00000309086, 70.7107],
              Biomes: ["ice_boss"]
            },
            {
              name: "Xylcor Beta",
              starting_planet: true,
              mass: 5000,
              Thrust: [1, 3],
              Radius: [300, 300],
              Height: [20, 25],
              Water: [0, 10],
              Temp: [0, 100],
              MetalDensity: [0, 25],
              MetalClusters: [0, 25],
              BiomeScale: [100, 100],
              Position: [100000, -10000],
              Velocity: [158.1139, 70.7106],
              Biomes: ["tropical"]
            },
            {
              name: "Xylcor Gamma",
              starting_planet: false,
              mass: 5000,
              Thrust: [0, 0],
              Radius: [1500, 1500],
              Height: [0, 0],
              Water: [0, 0],
              Temp: [0, 100],
              MetalDensity: [0, 0],
              MetalClusters: [0, 0],
              BiomeScale: [0, 0],
              Position: [110000, 0],
              Velocity: [0, 228.8246],
              Biomes: ["gas"]
            },
            {
              name: "Xylcor Delta",
              starting_planet: false,
              mass: 5000,
              Thrust: [0, 0],
              Radius: [1500, 1500],
              Height: [0, 0],
              Water: [0, 0],
              Temp: [0, 100],
              MetalDensity: [0, 0],
              MetalClusters: [0, 0],
              BiomeScale: [0, 0],
              Position: [90000, 0],
              Velocity: [0, -87.4032],
              Biomes: ["gas"]
            }
          ]
        }
      },
      {
        name: "Blogar's Fist - Foundation",
        boss: {
          name: "Inquisitor Nemicus",
          character: "Boss",
          econ_rate: 1.25,
          landing_policy: ["off_player_planet", "on_player_planet"],
          personality: {
            percent_open_vehicle: 0.33,
            percent_open_bot: 0.33,
            percent_open_air: 0.33,
            percent_open_naval: 0,
            percent_open_orbital: 0,
            percent_land: 0.05,
            percent_orbital: 0.4,
            percent_air: 0.55,
            percent_naval: 0,
            metal_drain_check: 0.54,
            energy_drain_check: 0.65,
            metal_demand_check: 0.71,
            energy_demand_check: 0.8,
            micro_type: 2,
            go_for_the_kill: true,
            neural_data_mod: 1,
            adv_eco_mod: 1,
            adv_eco_mod_alone: 0,
            fabber_to_factory_ratio_basic: 2,
            fabber_to_factory_ratio_advanced: 2,
            fabber_alone_on_planet_mod: 3,
            basic_to_advanced_factory_ratio: 0,
            factory_alone_on_planet_mod: 0.5,
            min_basic_fabbers: 3,
            min_advanced_fabbers: 1
          },
          commander: "/pa/units/commanders/raptor_nemicus/raptor_nemicus.json"
        },
        systemDescription:
          "!LOC:In researching ancient progenitor artifacts and data caches, Nemicus and his followers discovered references to The Great Machine. Supposedly, The Great Machine was what built and directed the commanders long ago. If any answers about the origins and purpose of the commanders were to be found, The Great Machine seemed like the best place to start.",
        systemTemplate: {
          name: "Blogar's Fist - Foundation",
          Planets: [
            {
              name: "Blogar's Fist Prime",
              starting_planet: true,
              mass: 50000,
              Thrust: [0, 0],
              Radius: [550, 650],
              Height: [20, 25],
              Water: [0, 10],
              Temp: [0, 100],
              MetalDensity: [25, 75],
              MetalClusters: [25, 50],
              BiomeScale: [100, 100],
              Position: [100000, 0],
              Velocity: [-0.00000309086, 70.7107],
              Biomes: ["ice_boss"]
            },
            {
              name: "Blogar's Fist Beta",
              starting_planet: true,
              mass: 5000,
              Thrust: [1, 3],
              Radius: [300, 300],
              Height: [20, 25],
              Water: [0, 10],
              Temp: [0, 100],
              MetalDensity: [0, 25],
              MetalClusters: [0, 25],
              BiomeScale: [100, 100],
              Position: [100000, -10000],
              Velocity: [158.1139, 70.7106],
              Biomes: ["tropical"]
            },
            {
              name: "Blogar's Fist Gamma",
              starting_planet: false,
              mass: 5000,
              Thrust: [0, 0],
              Radius: [1500, 1500],
              Height: [0, 0],
              Water: [0, 0],
              Temp: [0, 100],
              MetalDensity: [0, 0],
              MetalClusters: [0, 0],
              BiomeScale: [0, 0],
              Position: [110000, 0],
              Velocity: [0, 228.8246],
              Biomes: ["gas"]
            },
            {
              name: "Blogar's Fist Delta",
              starting_planet: false,
              mass: 5000,
              Thrust: [0, 0],
              Radius: [1500, 1500],
              Height: [0, 0],
              Water: [0, 0],
              Temp: [0, 100],
              MetalDensity: [0, 0],
              MetalClusters: [0, 0],
              BiomeScale: [0, 0],
              Position: [90000, 0],
              Velocity: [0, -87.4032],
              Biomes: ["gas"]
            }
          ]
        }
      },
      {
        name: "Zeta Draconis - Foundation",
        boss: {
          name: "Inquisitor Nemicus",
          character: "Boss",
          econ_rate: 1.25,
          landing_policy: ["off_player_planet", "on_player_planet"],
          personality: {
            percent_open_vehicle: 0.33,
            percent_open_bot: 0.33,
            percent_open_air: 0.33,
            percent_open_naval: 0,
            percent_open_orbital: 0,
            percent_land: 0.05,
            percent_orbital: 0.4,
            percent_air: 0.55,
            percent_naval: 0,
            metal_drain_check: 0.54,
            energy_drain_check: 0.65,
            metal_demand_check: 0.71,
            energy_demand_check: 0.8,
            micro_type: 2,
            go_for_the_kill: true,
            neural_data_mod: 1,
            adv_eco_mod: 1,
            adv_eco_mod_alone: 0,
            fabber_to_factory_ratio_basic: 2,
            fabber_to_factory_ratio_advanced: 2,
            fabber_alone_on_planet_mod: 3,
            basic_to_advanced_factory_ratio: 0,
            factory_alone_on_planet_mod: 0.5,
            min_basic_fabbers: 3,
            min_advanced_fabbers: 1
          },
          commander: "/pa/units/commanders/raptor_nemicus/raptor_nemicus.json"
        },
        systemDescription:
          "!LOC:The prevailing belief among The Foundation is that The Great Machine still 'lives' through data buried deep in the first directives given to the commanders. Because of this, Acolytes will often seek direction from The Great Machine by searching within their data banks in a form of meditation.",
        systemTemplate: {
          name: "Zeta Draconis - Foundation",
          Planets: [
            {
              name: "Zeta Draconis Prime",
              starting_planet: true,
              mass: 50000,
              Thrust: [0, 0],
              Radius: [550, 650],
              Height: [20, 25],
              Water: [0, 10],
              Temp: [0, 100],
              MetalDensity: [25, 75],
              MetalClusters: [25, 50],
              BiomeScale: [100, 100],
              Position: [100000, 0],
              Velocity: [-0.00000309086, 70.7107],
              Biomes: ["ice_boss"]
            },
            {
              name: "Zeta Draconis Beta",
              starting_planet: true,
              mass: 5000,
              Thrust: [1, 3],
              Radius: [300, 300],
              Height: [20, 25],
              Water: [0, 10],
              Temp: [0, 100],
              MetalDensity: [0, 25],
              MetalClusters: [0, 25],
              BiomeScale: [100, 100],
              Position: [100000, -10000],
              Velocity: [158.1139, 70.7106],
              Biomes: ["tropical"]
            },
            {
              name: "Zeta Draconis Gamma",
              starting_planet: false,
              mass: 5000,
              Thrust: [0, 0],
              Radius: [1500, 1500],
              Height: [0, 0],
              Water: [0, 0],
              Temp: [0, 100],
              MetalDensity: [0, 0],
              MetalClusters: [0, 0],
              BiomeScale: [0, 0],
              Position: [110000, 0],
              Velocity: [0, 228.8246],
              Biomes: ["gas"]
            },
            {
              name: "Zeta Draconis Delta",
              starting_planet: false,
              mass: 5000,
              Thrust: [0, 0],
              Radius: [1500, 1500],
              Height: [0, 0],
              Water: [0, 0],
              Temp: [0, 100],
              MetalDensity: [0, 0],
              MetalClusters: [0, 0],
              BiomeScale: [0, 0],
              Position: [90000, 0],
              Velocity: [0, -87.4032],
              Biomes: ["gas"]
            }
          ]
        }
      }
    ], // teams
    minions: [
      {
        // All Air
        name: "Acolyte Progenitor",
        character: "Air Force",
        color: [[229, 204, 255], [192, 192, 192]],
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0,
          percent_open_bot: 0,
          percent_open_air: 1,
          percent_open_naval: 0,
          percent_open_orbital: 0,
          percent_land: 0,
          percent_air: 1,
          percent_naval: 0,
          percent_orbital: 0,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.3,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 10
        },
        commander:
          "/pa/units/commanders/imperial_progenitor/imperial_progenitor.json"
      },
      {
        // All Naval
        name: "Acolyte Sangudo",
        character: "Navy",
        color: [[204, 153, 255], [192, 192, 192]],
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0,
          percent_open_bot: 0,
          percent_open_air: 0,
          percent_open_naval: 1,
          percent_open_orbital: 0,
          percent_land: 0,
          percent_air: 0,
          percent_naval: 1,
          percent_orbital: 0,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.3,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 10
        },
        commander: "/pa/units/commanders/imperial_sangudo/imperial_sangudo.json"
      },
      {
        // Uber
        name: "Acolyte Seniorhelix",
        character: "Uber",
        color: [[178, 102, 255], [192, 192, 192]],
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.05,
          percent_open_bot: 0.9,
          percent_open_air: 0,
          percent_open_naval: 0.05,
          percent_open_orbital: 0,
          percent_bot: 0.01,
          percent_vehicle: 0.04,
          percent_air: 0.5,
          percent_naval: 0.45,
          percent_orbital: 0,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.85,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1,
          adv_eco_mod_alone: 0,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 2,
          fabber_alone_on_planet_mod: 3,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 3,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 1,
          max_advanced_fabbers: 10
        },
        commander:
          "/pa/units/commanders/imperial_seniorhelix/imperial_seniorhelix.json"
      },
      {
        // Platinum
        name: "Acolyte Stelarch",
        character: "Platinum",
        color: [[153, 51, 255], [192, 192, 192]],
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.05,
          percent_open_bot: 0.9,
          percent_open_air: 0,
          percent_open_naval: 0.05,
          percent_open_orbital: 0,
          percent_bot: 0.01,
          percent_vehicle: 0.04,
          percent_air: 0.5,
          percent_naval: 0.45,
          percent_orbital: 0,
          metal_drain_check: 0.54,
          energy_drain_check: 0.77,
          metal_demand_check: 0.85,
          energy_demand_check: 0.92,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1.15,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1,
          adv_eco_mod_alone: 0,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 2,
          fabber_alone_on_planet_mod: 3,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 2,
          max_advanced_fabbers: 10
        },
        commander:
          "/pa/units/commanders/imperial_stelarch/imperial_stelarch.json"
      },
      {
        // Gold
        name: "Acolyte TheChessKnight",
        character: "Gold",
        color: [[127, 0, 255], [192, 192, 192]],
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.34,
          percent_open_bot: 0.34,
          percent_open_air: 0,
          percent_open_naval: 0.32,
          percent_open_orbital: 0,
          percent_land: 0.05,
          percent_air: 0.5,
          percent_naval: 0.45,
          percent_orbital: 0,
          metal_drain_check: 0.54,
          energy_drain_check: 0.77,
          metal_demand_check: 0.85,
          energy_demand_check: 0.92,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1.3,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1,
          adv_eco_mod_alone: 0,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 0.5,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 3,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 3,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 2,
          max_advanced_fabbers: 10
        },
        commander:
          "/pa/units/commanders/imperial_thechessknight/imperial_thechessknight.json"
      },
      {
        // Silver
        name: "Acolyte Theta",
        character: "Silver",
        color: [[102, 0, 204], [192, 192, 192]],
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.25,
          percent_open_bot: 0.25,
          percent_open_air: 0.25,
          percent_open_naval: 0.25,
          percent_open_orbital: 0,
          percent_land: 0.05,
          percent_air: 0.5,
          percent_naval: 0.45,
          percent_orbital: 0,
          metal_drain_check: 0.54,
          energy_drain_check: 0.77,
          metal_demand_check: 0.95,
          energy_demand_check: 0.92,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1.45,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1,
          adv_eco_mod_alone: 0,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 2,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 1,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 4,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 10
        },
        commander: "/pa/units/commanders/imperial_theta/imperial_theta.json"
      },
      {
        // Basic Tech
        name: "Acolyte ToddFather",
        character: "Luddite",
        color: [[76, 0, 153], [192, 192, 192]],
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.45,
          percent_open_bot: 0.45,
          percent_open_air: 0.05,
          percent_open_naval: 0.05,
          percent_open_orbital: 0,
          percent_land: 0.05,
          percent_air: 0.5,
          percent_naval: 0.45,
          percent_orbital: 0,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 3,
          adv_eco_mod_alone: 3,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 10
        },
        commander:
          "/pa/units/commanders/imperial_toddfather/imperial_toddfather.json"
      },
      {
        // Advanced Tech
        name: "Acolyte Ajax",
        character: "Technologist",
        color: [[255, 204, 255], [192, 192, 192]],
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.45,
          percent_open_bot: 0.45,
          percent_open_air: 0.05,
          percent_open_naval: 0.05,
          percent_open_orbital: 0,
          percent_land: 0.05,
          percent_air: 0.5,
          percent_naval: 0.45,
          percent_orbital: 0,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 0.5,
          adv_eco_mod_alone: 0,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 3,
          fabber_to_factory_ratio_advanced: 2,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 4,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 1,
          max_advanced_fabbers: 10
        },
        commander: "/pa/units/commanders/quad_ajax/quad_ajax.json"
      },
      {
        // Cautious
        name: "Acolyte Armalisk",
        character: "Cautious",
        color: [[255, 153, 255], [192, 192, 192]],
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.45,
          percent_open_bot: 0.45,
          percent_open_air: 0.05,
          percent_open_naval: 0.05,
          percent_open_orbital: 0,
          percent_land: 0.05,
          percent_air: 0.5,
          percent_naval: 0.45,
          percent_orbital: 0,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 0.75,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.3,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 4,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 2,
          max_advanced_fabbers: 10
        },
        commander: "/pa/units/commanders/quad_armalisk/quad_armalisk.json"
      },
      {
        // Aggressive
        name: "Acolyte Calyx",
        character: "Aggressive",
        color: [[255, 102, 255], [192, 192, 192]],
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.45,
          percent_open_bot: 0.45,
          percent_open_air: 0.05,
          percent_open_naval: 0.05,
          percent_open_orbital: 0,
          percent_land: 0.05,
          percent_air: 0.5,
          percent_naval: 0.45,
          percent_orbital: 0,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 2,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.3,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 10
        },
        commander: "/pa/units/commanders/quad_calyx/quad_calyx.json"
      },
      {
        // Rush
        name: "Acolyte Gambitdfa",
        character: "Rush",
        color: [[255, 0, 255], [192, 192, 192]],
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0,
          percent_open_bot: 0.9,
          percent_open_air: 0.05,
          percent_open_naval: 0.05,
          percent_open_orbital: 0,
          percent_land: 0.05,
          percent_air: 0.5,
          percent_naval: 0.45,
          percent_orbital: 0,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1.5,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 2,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 1,
          max_advanced_fabbers: 10
        },
        commander: "/pa/units/commanders/quad_gambitdfa/quad_gambitdfa.json"
      },
      {
        // Turtle
        name: "Acolyte Berlinetta",
        character: "Turtle",
        color: [[204, 0, 204], [192, 192, 192]],
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.9,
          percent_open_bot: 0,
          percent_open_air: 0.05,
          percent_open_naval: 0.05,
          percent_open_orbital: 0,
          percent_land: 0.05,
          percent_air: 0.5,
          percent_naval: 0.45,
          percent_orbital: 0,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 0.5,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 0.85,
          adv_eco_mod_alone: 0,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 5,
          fabber_to_factory_ratio_advanced: 5,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 5,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 4,
          max_advanced_fabbers: 10
        },
        commander:
          "/pa/units/commanders/quad_mobiousblack/quad_mobiousblack.json"
      },
      {
        // Original
        name: "Acolyte Osiris",
        character: "Original",
        color: [[153, 0, 153], [192, 192, 192]],
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.025,
          percent_open_bot: 0.025,
          percent_open_air: 0.55,
          percent_open_naval: 0.35,
          percent_open_orbital: 0,
          percent_land: 0.05,
          percent_orbital: 0.05,
          percent_air: 0.55,
          percent_naval: 0.35,
          metal_drain_check: 0.75,
          energy_drain_check: 0.85,
          metal_demand_check: 0.75,
          energy_demand_check: 0.85,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.3,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 10
        },
        commander: "/pa/units/commanders/quad_osiris/quad_osiris.json"
      },
      {
        // Absurd
        name: "Acolyte Tykus24",
        character: "Absurd",
        color: [[255, 204, 229], [192, 192, 192]],
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.13,
          percent_open_bot: 0.13,
          percent_open_air: 0.48,
          percent_open_naval: 0.26,
          percent_open_orbital: 0,
          percent_land: 0.25,
          percent_air: 0.45,
          percent_naval: 0.25,
          percent_orbital: 0.05,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.3,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 10
        },
        commander: "/pa/units/commanders/imperial_tykus24/imperial_tykus24.json"
      },
      {
        // Relentless
        name: "Acolyte Vidicarus",
        character: "Relentless",
        color: [[255, 153, 204], [192, 192, 192]],
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.13,
          percent_open_bot: 0.13,
          percent_open_air: 0.48,
          percent_open_naval: 0.26,
          percent_open_orbital: 0,
          percent_land: 0.25,
          percent_air: 0.45,
          percent_naval: 0.25,
          percent_orbital: 0.05,
          metal_drain_check: 0.44,
          energy_drain_check: 0.55,
          metal_demand_check: 0.61,
          energy_demand_check: 0.7,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1.2,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.2,
          adv_eco_mod_alone: 0.95,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 10
        },
        commander:
          "/pa/units/commanders/imperial_vidicarus/imperial_vidicarus.json"
      },
      {
        // Hard
        name: "Acolyte Visionik",
        character: "Hard",
        color: [[255, 102, 178], [192, 192, 192]],
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.13,
          percent_open_bot: 0.13,
          percent_open_air: 0.48,
          percent_open_naval: 0.26,
          percent_open_orbital: 0,
          percent_land: 0.25,
          percent_air: 0.45,
          percent_naval: 0.25,
          percent_orbital: 0.05,
          metal_drain_check: 0.34,
          energy_drain_check: 0.45,
          metal_demand_check: 0.51,
          energy_demand_check: 0.6,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1.5,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.1,
          adv_eco_mod_alone: 1,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 1,
          factory_build_delay_max: 3,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 10
        },
        commander:
          "/pa/units/commanders/imperial_visionik/imperial_visionik.json"
      },
      {
        // Bronze
        name: "Acolyte Commandonut",
        character: "Bronze",
        color: [[255, 51, 153], [192, 192, 192]],
        econ_rate: 1,
        personality: {
          percent_open_vehicle: 0.25,
          percent_open_bot: 0.25,
          percent_open_air: 0.25,
          percent_open_naval: 0.25,
          percent_open_orbital: 0,
          percent_land: 0.05,
          percent_air: 0.7,
          percent_naval: 0.2,
          percent_orbital: 0.05,
          metal_drain_check: 0.54,
          energy_drain_check: 0.77,
          metal_demand_check: 0.95,
          energy_demand_check: 0.92,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1.6,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 0.5,
          adv_eco_mod_alone: 0,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 6,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 5,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 1,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 1,
          min_basic_fabbers: 5,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 10
        },
        commander: "/pa/units/commanders/quad_commandonut/quad_commandonut.json"
      }
    ] // minions
  };
});
