// !LOCNS:galactic_war
define([], function() {
  return {
    name: "Revenants",
    color: [[236, 34, 35], [192, 192, 192]],
    teams: [
      {
        name: "Alenquer - Revenants",
        boss: {
          name: "First Seeker Osiris",
          character: "Dreamer",
          econ_rate: 2,
          landing_policy: ["off_player_planet"],
          personality: {
            percent_land: 0.05,
            percent_air: 0,
            percent_naval: 0,
            percent_orbital: 0.95,
            metal_drain_check: 0.54,
            energy_drain_check: 0.57,
            metal_demand_check: 0.85,
            energy_demand_check: 0.82,
            micro_type: 2,
            go_for_the_kill: true,
            neural_data_mod: 1,
            adv_eco_mod: 1,
            adv_eco_mod_alone: 0,
            fabber_to_factory_ratio_basic: 2,
            fabber_to_factory_ratio_advanced: 2,
            fabber_alone_on_planet_mod: 3,
            basic_to_advanced_factory_ratio: 0,
            factory_alone_on_planet_mod: 0.5,
            min_basic_fabbers: 5,
            min_advanced_fabbers: 1
          },
          commander: "/pa/units/commanders/quad_osiris/quad_osiris.json",
          minions: [
            {
              name: "Seeker Ankou",
              character: "Armour",
              econ_rate: 1.2,
              landing_policy: ["on_player_planet"],
              color: [[244, 124, 125], [192, 192, 192]],
              personality: {
                percent_vehicle: 0.9,
                percent_bot: 0,
                percent_air: 0.05,
                percent_naval: 0,
                percent_orbital: 0.05,
                metal_drain_check: 0.54,
                energy_drain_check: 0.57,
                metal_demand_check: 0.85,
                energy_demand_check: 0.82,
                micro_type: 2,
                go_for_the_kill: true,
                neural_data_mod: 1,
                adv_eco_mod: 1,
                adv_eco_mod_alone: 0,
                fabber_to_factory_ratio_basic: 1,
                fabber_to_factory_ratio_advanced: 2,
                fabber_alone_on_planet_mod: 3,
                basic_to_advanced_factory_ratio: 0,
                factory_alone_on_planet_mod: 0.5,
                min_basic_fabbers: 3,
                min_advanced_fabbers: 1
              },
              commander:
                "/pa/units/commanders/quad_spiderofmean/quad_spiderofmean.json"
            },
            {
              name: "Seeker Barastyr",
              character: "Infantry",
              econ_rate: 1.2,
              landing_policy: ["on_player_planet"],
              color: [[168, 0, 0], [192, 192, 192]],
              personality: {
                percent_vehicle: 0,
                percent_bot: 0.9,
                percent_air: 0.05,
                percent_naval: 0,
                percent_orbital: 0.05,
                metal_drain_check: 0.54,
                energy_drain_check: 0.57,
                metal_demand_check: 0.85,
                energy_demand_check: 0.82,
                micro_type: 2,
                go_for_the_kill: true,
                neural_data_mod: 1,
                adv_eco_mod: 1,
                adv_eco_mod_alone: 0,
                fabber_to_factory_ratio_basic: 1,
                fabber_to_factory_ratio_advanced: 2,
                fabber_alone_on_planet_mod: 3,
                basic_to_advanced_factory_ratio: 0,
                factory_alone_on_planet_mod: 0.5,
                min_basic_fabbers: 3,
                min_advanced_fabbers: 1
              },
              commander:
                "/pa/units/commanders/quad_xenosentryprime/quad_xenosentryprime.json"
            }
          ]
        },
        bossCard: "gwc_start_orbital",
        systemDescription:
          "!LOC:Osiris has always lead a solitary existence. He was always more interested in the parts of his fellow commanders than the commanders themselves. With every battle won he would take the best pieces left of the broken adversary and integrate them into his form. Osiris is considered one of the most dangerous forces in the galaxy.",
        systemTemplate: {
          name: "Alenquer - Revenants",
          Planets: [
            {
              name: "Alenquer Prime",
              starting_planet: true,
              mass: 50000,
              Thrust: [0, 0],
              Radius: [600, 800],
              Height: [20, 25],
              Water: [0, 10],
              Temp: [0, 100],
              MetalDensity: [100, 100],
              MetalClusters: [24, 49],
              BiomeScale: [100, 100],
              Position: [40000, 0],
              Velocity: [0, 111.803],
              Biomes: ["metal"]
            },
            {
              name: "Alenquer Beta",
              starting_planet: true,
              mass: 5000,
              Thrust: [0, 0],
              Radius: [225, 225],
              Height: [0, 10],
              Water: [0, 10],
              Temp: [0, 100],
              MetalDensity: [100, 100],
              MetalClusters: [100, 100],
              BiomeScale: [100, 100],
              Position: [40000, -5000],
              Velocity: [-223.6067, 111.80299],
              Biomes: ["moon"]
            },
            {
              name: "Alenquer Gamma",
              starting_planet: true,
              mass: 5000,
              Thrust: [0, 0],
              Radius: [225, 225],
              Height: [0, 10],
              Water: [0, 10],
              Temp: [0, 100],
              MetalDensity: [100, 100],
              MetalClusters: [100, 100],
              BiomeScale: [100, 100],
              Position: [35700, 2500],
              Velocity: [112.683, 305.6186],
              Biomes: ["moon"]
            },
            {
              name: "Alenquer Delta",
              starting_planet: true,
              mass: 5000,
              Thrust: [0, 0],
              Radius: [225, 225],
              Height: [0, 10],
              Water: [0, 10],
              Temp: [0, 100],
              MetalDensity: [100, 100],
              MetalClusters: [100, 100],
              BiomeScale: [100, 100],
              Position: [44300, 2500],
              Velocity: [112.683, -82.0126],
              Biomes: ["moon"]
            }
          ]
        }
      },
      {
        name: "Xianyao - Revenants",
        boss: {
          name: "First Seeker Osiris",
          character: "Dreamer",
          econ_rate: 2,
          landing_policy: ["off_player_planet"],
          personality: {
            percent_land: 0.05,
            percent_air: 0,
            percent_naval: 0,
            percent_orbital: 0.95,
            metal_drain_check: 0.54,
            energy_drain_check: 0.57,
            metal_demand_check: 0.85,
            energy_demand_check: 0.82,
            micro_type: 2,
            go_for_the_kill: true,
            neural_data_mod: 1,
            adv_eco_mod: 1,
            adv_eco_mod_alone: 0,
            fabber_to_factory_ratio_basic: 2,
            fabber_to_factory_ratio_advanced: 2,
            fabber_alone_on_planet_mod: 3,
            basic_to_advanced_factory_ratio: 0,
            factory_alone_on_planet_mod: 0.5,
            min_basic_fabbers: 5,
            min_advanced_fabbers: 1
          },
          commander: "/pa/units/commanders/quad_osiris/quad_osiris.json",
          minions: [
            {
              name: "Seeker Ankou",
              character: "Armour",
              econ_rate: 1.2,
              landing_policy: ["on_player_planet"],
              color: [[244, 124, 125], [192, 192, 192]],
              personality: {
                percent_vehicle: 0.9,
                percent_bot: 0,
                percent_air: 0.05,
                percent_naval: 0,
                percent_orbital: 0.05,
                metal_drain_check: 0.54,
                energy_drain_check: 0.57,
                metal_demand_check: 0.85,
                energy_demand_check: 0.82,
                micro_type: 2,
                go_for_the_kill: true,
                neural_data_mod: 1,
                adv_eco_mod: 1,
                adv_eco_mod_alone: 0,
                fabber_to_factory_ratio_basic: 1,
                fabber_to_factory_ratio_advanced: 2,
                fabber_alone_on_planet_mod: 3,
                basic_to_advanced_factory_ratio: 0,
                factory_alone_on_planet_mod: 0.5,
                min_basic_fabbers: 3,
                min_advanced_fabbers: 1
              },
              commander:
                "/pa/units/commanders/quad_spiderofmean/quad_spiderofmean.json"
            },
            {
              name: "Seeker Barastyr",
              character: "Infantry",
              econ_rate: 1.2,
              landing_policy: ["on_player_planet"],
              color: [[168, 0, 0], [192, 192, 192]],
              personality: {
                percent_vehicle: 0,
                percent_bot: 0.9,
                percent_air: 0.05,
                percent_naval: 0,
                percent_orbital: 0.05,
                metal_drain_check: 0.54,
                energy_drain_check: 0.57,
                metal_demand_check: 0.85,
                energy_demand_check: 0.82,
                micro_type: 2,
                go_for_the_kill: true,
                neural_data_mod: 1,
                adv_eco_mod: 1,
                adv_eco_mod_alone: 0,
                fabber_to_factory_ratio_basic: 1,
                fabber_to_factory_ratio_advanced: 2,
                fabber_alone_on_planet_mod: 3,
                basic_to_advanced_factory_ratio: 0,
                factory_alone_on_planet_mod: 0.5,
                min_basic_fabbers: 3,
                min_advanced_fabbers: 1
              },
              commander:
                "/pa/units/commanders/quad_xenosentryprime/quad_xenosentryprime.json"
            }
          ]
        },
        bossCard: "gwc_start_subcdr",
        systemDescription:
          "!LOC:As Osiris replaced pieces of himself with those of fallen foes, he would store older parts for replacements and repairs. Eventually, Osiris acquired enough spare parts to construct an entirely new commander. This would be the birth of the first Seeker.",
        systemTemplate: {
          name: "Xianyao - Revenants",
          Planets: [
            {
              name: "Xianyao Prime",
              starting_planet: true,
              mass: 50000,
              Thrust: [0, 0],
              Radius: [600, 800],
              Height: [20, 25],
              Water: [0, 10],
              Temp: [0, 100],
              MetalDensity: [100, 100],
              MetalClusters: [24, 49],
              BiomeScale: [100, 100],
              Position: [40000, 0],
              Velocity: [0, 111.803],
              Biomes: ["metal"]
            },
            {
              name: "Xianyao Beta",
              starting_planet: true,
              mass: 5000,
              Thrust: [0, 0],
              Radius: [225, 225],
              Height: [0, 10],
              Water: [0, 10],
              Temp: [0, 100],
              MetalDensity: [100, 100],
              MetalClusters: [100, 100],
              BiomeScale: [100, 100],
              Position: [40000, -5000],
              Velocity: [-223.6067, 111.80299],
              Biomes: ["moon"]
            },
            {
              name: "Xianyao Gamma",
              starting_planet: true,
              mass: 5000,
              Thrust: [0, 0],
              Radius: [225, 225],
              Height: [0, 10],
              Water: [0, 10],
              Temp: [0, 100],
              MetalDensity: [100, 100],
              MetalClusters: [100, 100],
              BiomeScale: [100, 100],
              Position: [35700, 2500],
              Velocity: [112.683, 305.6186],
              Biomes: ["moon"]
            },
            {
              name: "Xianyao Delta",
              starting_planet: true,
              mass: 5000,
              Thrust: [0, 0],
              Radius: [225, 225],
              Height: [0, 10],
              Water: [0, 10],
              Temp: [0, 100],
              MetalDensity: [100, 100],
              MetalClusters: [100, 100],
              BiomeScale: [100, 100],
              Position: [44300, 2500],
              Velocity: [112.683, -82.0126],
              Biomes: ["moon"]
            }
          ]
        }
      },
      {
        name: "Epiphany - Revenants",
        boss: {
          name: "First Seeker Osiris",
          character: "Dreamer",
          econ_rate: 2,
          landing_policy: ["off_player_planet"],
          personality: {
            percent_land: 0.05,
            percent_air: 0,
            percent_naval: 0,
            percent_orbital: 0.95,
            metal_drain_check: 0.54,
            energy_drain_check: 0.57,
            metal_demand_check: 0.85,
            energy_demand_check: 0.82,
            micro_type: 2,
            go_for_the_kill: true,
            neural_data_mod: 1,
            adv_eco_mod: 1,
            adv_eco_mod_alone: 0,
            fabber_to_factory_ratio_basic: 2,
            fabber_to_factory_ratio_advanced: 2,
            fabber_alone_on_planet_mod: 3,
            basic_to_advanced_factory_ratio: 0,
            factory_alone_on_planet_mod: 0.5,
            min_basic_fabbers: 5,
            min_advanced_fabbers: 1
          },
          commander: "/pa/units/commanders/quad_osiris/quad_osiris.json",
          minions: [
            {
              name: "Seeker Ankou",
              character: "Armour",
              econ_rate: 1.2,
              landing_policy: ["on_player_planet"],
              color: [[244, 124, 125], [192, 192, 192]],
              personality: {
                percent_vehicle: 0.9,
                percent_bot: 0,
                percent_air: 0.05,
                percent_naval: 0,
                percent_orbital: 0.05,
                metal_drain_check: 0.54,
                energy_drain_check: 0.57,
                metal_demand_check: 0.85,
                energy_demand_check: 0.82,
                micro_type: 2,
                go_for_the_kill: true,
                neural_data_mod: 1,
                adv_eco_mod: 1,
                adv_eco_mod_alone: 0,
                fabber_to_factory_ratio_basic: 1,
                fabber_to_factory_ratio_advanced: 2,
                fabber_alone_on_planet_mod: 3,
                basic_to_advanced_factory_ratio: 0,
                factory_alone_on_planet_mod: 0.5,
                min_basic_fabbers: 3,
                min_advanced_fabbers: 1
              },
              commander:
                "/pa/units/commanders/quad_spiderofmean/quad_spiderofmean.json"
            },
            {
              name: "Seeker Barastyr",
              character: "Infantry",
              econ_rate: 1.2,
              landing_policy: ["on_player_planet"],
              color: [[168, 0, 0], [192, 192, 192]],
              personality: {
                percent_vehicle: 0,
                percent_bot: 0.9,
                percent_air: 0.05,
                percent_naval: 0,
                percent_orbital: 0.05,
                metal_drain_check: 0.54,
                energy_drain_check: 0.57,
                metal_demand_check: 0.85,
                energy_demand_check: 0.82,
                micro_type: 2,
                go_for_the_kill: true,
                neural_data_mod: 1,
                adv_eco_mod: 1,
                adv_eco_mod_alone: 0,
                fabber_to_factory_ratio_basic: 1,
                fabber_to_factory_ratio_advanced: 2,
                fabber_alone_on_planet_mod: 3,
                basic_to_advanced_factory_ratio: 0,
                factory_alone_on_planet_mod: 0.5,
                min_basic_fabbers: 3,
                min_advanced_fabbers: 1
              },
              commander:
                "/pa/units/commanders/quad_xenosentryprime/quad_xenosentryprime.json"
            }
          ]
        },
        //bossCard: 'gwc_start_orbital',
        systemDescription:
          "!LOC:The Revenants are unique in that their motivations are individual rather than collective. Each Seeker follows in the example of their legendary Osiris--they seek battle to become stronger through their fallen enemies, and to create more Revenants.",
        systemTemplate: {
          name: "Epiphany - Revenants",
          Planets: [
            {
              name: "Epiphany Prime",
              starting_planet: true,
              mass: 50000,
              Thrust: [0, 0],
              Radius: [600, 800],
              Height: [20, 25],
              Water: [0, 10],
              Temp: [0, 100],
              MetalDensity: [100, 100],
              MetalClusters: [24, 49],
              BiomeScale: [100, 100],
              Position: [40000, 0],
              Velocity: [0, 111.803],
              Biomes: ["metal"]
            },
            {
              name: "Epiphany Beta",
              starting_planet: true,
              mass: 5000,
              Thrust: [0, 0],
              Radius: [225, 225],
              Height: [0, 10],
              Water: [0, 10],
              Temp: [0, 100],
              MetalDensity: [100, 100],
              MetalClusters: [100, 100],
              BiomeScale: [100, 100],
              Position: [40000, -5000],
              Velocity: [-223.6067, 111.80299],
              Biomes: ["moon"]
            },
            {
              name: "Epiphany Gamma",
              starting_planet: true,
              mass: 5000,
              Thrust: [0, 0],
              Radius: [225, 225],
              Height: [0, 10],
              Water: [0, 10],
              Temp: [0, 100],
              MetalDensity: [100, 100],
              MetalClusters: [100, 100],
              BiomeScale: [100, 100],
              Position: [35700, 2500],
              Velocity: [112.683, 305.6186],
              Biomes: ["moon"]
            },
            {
              name: "Epiphany Delta",
              starting_planet: true,
              mass: 5000,
              Thrust: [0, 0],
              Radius: [225, 225],
              Height: [0, 10],
              Water: [0, 10],
              Temp: [0, 100],
              MetalDensity: [100, 100],
              MetalClusters: [100, 100],
              BiomeScale: [100, 100],
              Position: [44300, 2500],
              Velocity: [112.683, -82.0126],
              Biomes: ["moon"]
            }
          ]
        }
      },
      {
        name: "Varthema - Revenants",
        boss: {
          name: "First Seeker Osiris",
          character: "Dreamer",
          econ_rate: 2,
          landing_policy: ["off_player_planet"],
          personality: {
            percent_land: 0.05,
            percent_air: 0,
            percent_naval: 0,
            percent_orbital: 0.95,
            metal_drain_check: 0.54,
            energy_drain_check: 0.57,
            metal_demand_check: 0.85,
            energy_demand_check: 0.82,
            micro_type: 2,
            go_for_the_kill: true,
            neural_data_mod: 1,
            adv_eco_mod: 1,
            adv_eco_mod_alone: 0,
            fabber_to_factory_ratio_basic: 2,
            fabber_to_factory_ratio_advanced: 2,
            fabber_alone_on_planet_mod: 3,
            basic_to_advanced_factory_ratio: 0,
            factory_alone_on_planet_mod: 0.5,
            min_basic_fabbers: 5,
            min_advanced_fabbers: 1
          },
          commander: "/pa/units/commanders/quad_osiris/quad_osiris.json",
          minions: [
            {
              name: "Seeker Ankou",
              character: "Armour",
              econ_rate: 1.2,
              landing_policy: ["on_player_planet"],
              color: [[244, 124, 125], [192, 192, 192]],
              personality: {
                percent_vehicle: 0.9,
                percent_bot: 0,
                percent_air: 0.05,
                percent_naval: 0,
                percent_orbital: 0.05,
                metal_drain_check: 0.54,
                energy_drain_check: 0.57,
                metal_demand_check: 0.85,
                energy_demand_check: 0.82,
                micro_type: 2,
                go_for_the_kill: true,
                neural_data_mod: 1,
                adv_eco_mod: 1,
                adv_eco_mod_alone: 0,
                fabber_to_factory_ratio_basic: 1,
                fabber_to_factory_ratio_advanced: 2,
                fabber_alone_on_planet_mod: 3,
                basic_to_advanced_factory_ratio: 0,
                factory_alone_on_planet_mod: 0.5,
                min_basic_fabbers: 3,
                min_advanced_fabbers: 1
              },
              commander:
                "/pa/units/commanders/quad_spiderofmean/quad_spiderofmean.json"
            },
            {
              name: "Seeker Barastyr",
              character: "Infantry",
              econ_rate: 1.2,
              landing_policy: ["on_player_planet"],
              color: [[168, 0, 0], [192, 192, 192]],
              personality: {
                percent_vehicle: 0,
                percent_bot: 0.9,
                percent_air: 0.05,
                percent_naval: 0,
                percent_orbital: 0.05,
                metal_drain_check: 0.54,
                energy_drain_check: 0.57,
                metal_demand_check: 0.85,
                energy_demand_check: 0.82,
                micro_type: 2,
                go_for_the_kill: true,
                neural_data_mod: 1,
                adv_eco_mod: 1,
                adv_eco_mod_alone: 0,
                fabber_to_factory_ratio_basic: 1,
                fabber_to_factory_ratio_advanced: 2,
                fabber_alone_on_planet_mod: 3,
                basic_to_advanced_factory_ratio: 0,
                factory_alone_on_planet_mod: 0.5,
                min_basic_fabbers: 3,
                min_advanced_fabbers: 1
              },
              commander:
                "/pa/units/commanders/quad_xenosentryprime/quad_xenosentryprime.json"
            }
          ]
        },
        //bossCard: 'gwc_start_orbital',
        systemDescription:
          "!LOC:Osiris holds no interest in ruling, and instead serves more as an exemplar, whether he cares to or not. Therefore, it falls to a small council of older Seekers to direct the affairs of The Revenants at large--primarily making sure that they're fighting the other factions instead of amongst themselves.",
        systemTemplate: {
          name: "Varthema - Revenants",
          Planets: [
            {
              name: "Varthema Prime",
              starting_planet: true,
              mass: 50000,
              Thrust: [0, 0],
              Radius: [600, 800],
              Height: [20, 25],
              Water: [0, 10],
              Temp: [0, 100],
              MetalDensity: [100, 100],
              MetalClusters: [24, 49],
              BiomeScale: [100, 100],
              Position: [40000, 0],
              Velocity: [0, 111.803],
              Biomes: ["metal"]
            },
            {
              name: "Varthema Beta",
              starting_planet: true,
              mass: 5000,
              Thrust: [0, 0],
              Radius: [225, 225],
              Height: [0, 10],
              Water: [0, 10],
              Temp: [0, 100],
              MetalDensity: [100, 100],
              MetalClusters: [100, 100],
              BiomeScale: [100, 100],
              Position: [40000, -5000],
              Velocity: [-223.6067, 111.80299],
              Biomes: ["moon"]
            },
            {
              name: "Varthema Gamma",
              starting_planet: true,
              mass: 5000,
              Thrust: [0, 0],
              Radius: [225, 225],
              Height: [0, 10],
              Water: [0, 10],
              Temp: [0, 100],
              MetalDensity: [100, 100],
              MetalClusters: [100, 100],
              BiomeScale: [100, 100],
              Position: [35700, 2500],
              Velocity: [112.683, 305.6186],
              Biomes: ["moon"]
            },
            {
              name: "Varthema Delta",
              starting_planet: true,
              mass: 5000,
              Thrust: [0, 0],
              Radius: [225, 225],
              Height: [0, 10],
              Water: [0, 10],
              Temp: [0, 100],
              MetalDensity: [100, 100],
              MetalClusters: [100, 100],
              BiomeScale: [100, 100],
              Position: [44300, 2500],
              Velocity: [112.683, -82.0126],
              Biomes: ["moon"]
            }
          ]
        }
      },
      {
        name: "Chernykh - Revenants",
        boss: {
          name: "First Seeker Osiris",
          character: "Dreamer",
          econ_rate: 2,
          landing_policy: ["off_player_planet"],
          personality: {
            percent_land: 0.05,
            percent_air: 0,
            percent_naval: 0,
            percent_orbital: 0.95,
            metal_drain_check: 0.54,
            energy_drain_check: 0.57,
            metal_demand_check: 0.85,
            energy_demand_check: 0.82,
            micro_type: 2,
            go_for_the_kill: true,
            neural_data_mod: 1,
            adv_eco_mod: 1,
            adv_eco_mod_alone: 0,
            fabber_to_factory_ratio_basic: 2,
            fabber_to_factory_ratio_advanced: 2,
            fabber_alone_on_planet_mod: 3,
            basic_to_advanced_factory_ratio: 0,
            factory_alone_on_planet_mod: 0.5,
            min_basic_fabbers: 5,
            min_advanced_fabbers: 1
          },
          commander: "/pa/units/commanders/quad_osiris/quad_osiris.json",
          minions: [
            {
              name: "Seeker Ankou",
              character: "Armour",
              econ_rate: 1.2,
              landing_policy: ["on_player_planet"],
              color: [[244, 124, 125], [192, 192, 192]],
              personality: {
                percent_vehicle: 0.9,
                percent_bot: 0,
                percent_air: 0.05,
                percent_naval: 0,
                percent_orbital: 0.05,
                metal_drain_check: 0.54,
                energy_drain_check: 0.57,
                metal_demand_check: 0.85,
                energy_demand_check: 0.82,
                micro_type: 2,
                go_for_the_kill: true,
                neural_data_mod: 1,
                adv_eco_mod: 1,
                adv_eco_mod_alone: 0,
                fabber_to_factory_ratio_basic: 1,
                fabber_to_factory_ratio_advanced: 2,
                fabber_alone_on_planet_mod: 3,
                basic_to_advanced_factory_ratio: 0,
                factory_alone_on_planet_mod: 0.5,
                min_basic_fabbers: 3,
                min_advanced_fabbers: 1
              },
              commander:
                "/pa/units/commanders/quad_spiderofmean/quad_spiderofmean.json"
            },
            {
              name: "Seeker Barastyr",
              character: "Infantry",
              econ_rate: 1.2,
              landing_policy: ["on_player_planet"],
              color: [[168, 0, 0], [192, 192, 192]],
              personality: {
                percent_vehicle: 0,
                percent_bot: 0.9,
                percent_air: 0.05,
                percent_naval: 0,
                percent_orbital: 0.05,
                metal_drain_check: 0.54,
                energy_drain_check: 0.57,
                metal_demand_check: 0.85,
                energy_demand_check: 0.82,
                micro_type: 2,
                go_for_the_kill: true,
                neural_data_mod: 1,
                adv_eco_mod: 1,
                adv_eco_mod_alone: 0,
                fabber_to_factory_ratio_basic: 1,
                fabber_to_factory_ratio_advanced: 2,
                fabber_alone_on_planet_mod: 3,
                basic_to_advanced_factory_ratio: 0,
                factory_alone_on_planet_mod: 0.5,
                min_basic_fabbers: 3,
                min_advanced_fabbers: 1
              },
              commander:
                "/pa/units/commanders/quad_xenosentryprime/quad_xenosentryprime.json"
            }
          ]
        },
        //bossCard: 'gwc_start_orbital',
        systemDescription:
          "!LOC:Osiris often considered the most dangerous commander in all the galaxy for the amount of annihilations he is credited with. A force of war equal to any army, high command of any faction takes his movements into consideration when deploying forces.",
        systemTemplate: {
          name: "Chernykh - Revenants",
          Planets: [
            {
              name: "Chernykh Prime",
              starting_planet: true,
              mass: 50000,
              Thrust: [0, 0],
              Radius: [600, 800],
              Height: [20, 25],
              Water: [0, 10],
              Temp: [0, 100],
              MetalDensity: [100, 100],
              MetalClusters: [24, 49],
              BiomeScale: [100, 100],
              Position: [40000, 0],
              Velocity: [0, 111.803],
              Biomes: ["metal"]
            },
            {
              name: "Chernykh Beta",
              starting_planet: true,
              mass: 5000,
              Thrust: [0, 0],
              Radius: [225, 225],
              Height: [0, 10],
              Water: [0, 10],
              Temp: [0, 100],
              MetalDensity: [100, 100],
              MetalClusters: [100, 100],
              BiomeScale: [100, 100],
              Position: [40000, -5000],
              Velocity: [-223.6067, 111.80299],
              Biomes: ["moon"]
            },
            {
              name: "Chernykh Gamma",
              starting_planet: true,
              mass: 5000,
              Thrust: [0, 0],
              Radius: [225, 225],
              Height: [0, 10],
              Water: [0, 10],
              Temp: [0, 100],
              MetalDensity: [100, 100],
              MetalClusters: [100, 100],
              BiomeScale: [100, 100],
              Position: [35700, 2500],
              Velocity: [112.683, 305.6186],
              Biomes: ["moon"]
            },
            {
              name: "Chernykh Delta",
              starting_planet: true,
              mass: 5000,
              Thrust: [0, 0],
              Radius: [225, 225],
              Height: [0, 10],
              Water: [0, 10],
              Temp: [0, 100],
              MetalDensity: [100, 100],
              MetalClusters: [100, 100],
              BiomeScale: [100, 100],
              Position: [44300, 2500],
              Velocity: [112.683, -82.0126],
              Biomes: ["moon"]
            }
          ]
        }
      }
    ], // teams
    minions: [
      {
        // Orbital & Land
        name: "Seeker Betadyne",
        character: "Orbital and Land",
        color: [[255, 204, 204], [192, 192, 192]],
        econ_rate: 1,
        personality: {
          percent_land: 0.5,
          percent_air: 0,
          percent_naval: 0,
          percent_orbital: 0.5,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.3,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 10
        },
        commander: "/pa/units/commanders/raptor_betadyne/raptor_betadyne.json"
      },
      {
        // Orbital & Air
        name: "Seeker Centurion",
        character: "Orbital and Air",
        color: [[255, 153, 153], [192, 192, 192]],
        econ_rate: 1,
        personality: {
          percent_land: 0,
          percent_air: 0.5,
          percent_naval: 0,
          percent_orbital: 0.5,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.3,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 10
        },
        commander: "/pa/units/commanders/raptor_centurion/raptor_centurion.json"
      },
      {
        // Uber
        name: "Seeker Diremachine",
        character: "Uber",
        color: [[255, 102, 102], [192, 192, 192]],
        econ_rate: 1,
        personality: {
          percent_land: 0.05,
          percent_air: 0,
          percent_naval: 0,
          percent_orbital: 0.95,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.85,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1,
          adv_eco_mod_alone: 0,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 2,
          fabber_alone_on_planet_mod: 3,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 3,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 1,
          max_advanced_fabbers: 10
        },
        commander:
          "/pa/units/commanders/raptor_diremachine/raptor_diremachine.json"
      },
      {
        // Platinum
        name: "Seeker Enderstryke71",
        character: "Platinum",
        color: [[255, 0, 0], [192, 192, 192]],
        econ_rate: 1,
        personality: {
          percent_land: 0.05,
          percent_air: 0,
          percent_naval: 0,
          percent_orbital: 0.95,
          metal_drain_check: 0.54,
          energy_drain_check: 0.77,
          metal_demand_check: 0.85,
          energy_demand_check: 0.92,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1.15,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1,
          adv_eco_mod_alone: 0,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 2,
          fabber_alone_on_planet_mod: 3,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 2,
          max_advanced_fabbers: 10
        },
        commander:
          "/pa/units/commanders/raptor_enderstryke71/raptor_enderstryke71.json"
      },
      {
        // Gold
        name: "Seeker Iwmiked",
        character: "Gold",
        color: [[204, 0, 0], [192, 192, 192]],
        econ_rate: 1,
        personality: {
          percent_land: 0.05,
          percent_air: 0,
          percent_naval: 0,
          percent_orbital: 0.95,
          metal_drain_check: 0.54,
          energy_drain_check: 0.77,
          metal_demand_check: 0.85,
          energy_demand_check: 0.92,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1.3,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1,
          adv_eco_mod_alone: 0,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 0.5,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 3,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 3,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 2,
          max_advanced_fabbers: 10
        },
        commander: "/pa/units/commanders/raptor_iwmiked/raptor_iwmiked.json"
      },
      {
        // Silver
        name: "Seeker Majuju",
        character: "Silver",
        color: [[153, 0, 0], [192, 192, 192]],
        econ_rate: 1,
        personality: {
          percent_land: 0.05,
          percent_air: 0,
          percent_naval: 0,
          percent_orbital: 0.95,
          metal_drain_check: 0.54,
          energy_drain_check: 0.77,
          metal_demand_check: 0.95,
          energy_demand_check: 0.92,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1.45,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1,
          adv_eco_mod_alone: 0,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 2,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 1,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 4,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 10
        },
        commander: "/pa/units/commanders/raptor_majuju/raptor_majuju.json"
      },
      {
        // Basic Tech
        name: "Seeker Nefelpitou",
        character: "Basic Tech",
        color: [[255, 204, 153], [192, 192, 192]],
        econ_rate: 1,
        personality: {
          percent_land: 0.05,
          percent_air: 0,
          percent_naval: 0,
          percent_orbital: 0.95,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 3,
          adv_eco_mod_alone: 3,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 10
        },
        commander:
          "/pa/units/commanders/raptor_nefelpitou/raptor_nefelpitou.json"
      },
      {
        // Advanced Tech
        name: "Seeker Nemicus",
        character: "Technologist",
        color: [[255, 178, 102], [192, 192, 192]],
        econ_rate: 1,
        personality: {
          percent_land: 0.05,
          percent_air: 0,
          percent_naval: 0,
          percent_orbital: 0.95,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 0.5,
          adv_eco_mod_alone: 0,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 2,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 4,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 1,
          max_advanced_fabbers: 10
        },
        commander: "/pa/units/commanders/raptor_nemicus/raptor_nemicus.json"
      },
      {
        // Cautious
        name: "Seeker Rallus",
        character: "Cautious",
        color: [[255, 153, 51], [192, 192, 192]],
        econ_rate: 1,
        personality: {
          percent_land: 0.05,
          percent_air: 0,
          percent_naval: 0,
          percent_orbital: 0.95,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 0.75,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.3,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 4,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 2,
          max_advanced_fabbers: 10
        },
        commander: "/pa/units/commanders/raptor_rallus/raptor_rallus.json"
      },
      {
        // Aggressive
        name: "Seeker Stickman9000",
        character: "Aggressive",
        color: [[255, 128, 0], [192, 192, 192]],
        econ_rate: 1,
        personality: {
          percent_land: 0.05,
          percent_air: 0,
          percent_naval: 0,
          percent_orbital: 0.95,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 2,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.3,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 10
        },
        commander:
          "/pa/units/commanders/raptor_stickman9000/raptor_stickman9000.json"
      },
      {
        // Rush
        name: "Seeker Zaazzaa",
        character: "Rush",
        color: [[204, 102, 0], [192, 192, 192]],
        econ_rate: 1,
        personality: {
          percent_bot: 0.05,
          percent_vehicle: 0,
          percent_air: 0,
          percent_naval: 0,
          percent_orbital: 0.95,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1.25,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 3,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 1,
          max_advanced_fabbers: 10
        },
        commander: "/pa/units/commanders/raptor_zaazzaa/raptor_zaazzaa.json"
      },
      {
        // Turtle
        name: "Seeker Aeson",
        character: "Turtle",
        color: [[255, 255, 204], [192, 192, 192]],
        econ_rate: 1,
        personality: {
          percent_land: 0.05,
          percent_air: 0,
          percent_naval: 0,
          percent_orbital: 0.95,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 0.5,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 0.85,
          adv_eco_mod_alone: 0,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 5,
          fabber_to_factory_ratio_advanced: 5,
          fabber_alone_on_planet_mod: 3,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 5,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 4,
          max_advanced_fabbers: 10
        },
        commander: "/pa/units/commanders/tank_aeson/tank_aeson.json"
      },
      {
        // Original
        name: "Seeker Banditks",
        character: "Original",
        color: [[255, 255, 153], [192, 192, 192]],
        econ_rate: 1,
        personality: {
          percent_land: 0.16,
          percent_air: 0.14,
          percent_naval: 0.1,
          percent_orbital: 0.6,
          metal_drain_check: 0.75,
          energy_drain_check: 0.85,
          metal_demand_check: 0.75,
          energy_demand_check: 0.85,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.3,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 10
        },
        commander: "/pa/units/commanders/tank_banditks/tank_banditks.json"
      },
      {
        // Absurd
        name: "Seeker SPZ58624",
        character: "Absurd",
        color: [[255, 255, 102], [192, 192, 192]],
        econ_rate: 1,
        personality: {
          percent_vehicle: 0.25,
          percent_bot: 0.2,
          percent_air: 0.05,
          percent_naval: 0.05,
          percent_orbital: 0.45,
          metal_drain_check: 0.54,
          energy_drain_check: 0.65,
          metal_demand_check: 0.71,
          energy_demand_check: 0.8,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.3,
          adv_eco_mod_alone: 0.85,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 10
        },
        commander: "/pa/units/commanders/raptor_spz58624/raptor_spz58624.json"
      },
      {
        // Relentless
        name: "Seeker XOV",
        character: "Relentless",
        color: [[255, 255, 0], [192, 192, 192]],
        econ_rate: 1,
        personality: {
          percent_vehicle: 0.25,
          percent_bot: 0.2,
          percent_air: 0.05,
          percent_naval: 0.05,
          percent_orbital: 0.45,
          metal_drain_check: 0.44,
          energy_drain_check: 0.55,
          metal_demand_check: 0.61,
          energy_demand_check: 0.7,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1.2,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.2,
          adv_eco_mod_alone: 0.95,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 0,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 10
        },
        commander: "/pa/units/commanders/raptor_xov/raptor_xov.json"
      },
      {
        // Hard
        name: "Seeker Reaver",
        character: "Hard",
        color: [[204, 204, 0], [192, 192, 192]],
        econ_rate: 1,
        personality: {
          percent_vehicle: 0.25,
          percent_bot: 0.2,
          percent_air: 0.05,
          percent_naval: 0.05,
          percent_orbital: 0.45,
          metal_drain_check: 0.34,
          energy_drain_check: 0.45,
          metal_demand_check: 0.51,
          energy_demand_check: 0.6,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1.5,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 1.1,
          adv_eco_mod_alone: 1,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 1,
          factory_build_delay_max: 3,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 1,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 2,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 0.5,
          min_basic_fabbers: 2,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 10
        },
        commander: "/pa/units/commanders/tank_reaver/tank_reaver.json"
      },
      {
        // Bronze
        name: "Seeker Sadiga",
        character: "Bronze",
        color: [[153, 153, 0], [192, 192, 192]],
        econ_rate: 1,
        personality: {
          percent_land: 0.2,
          percent_air: 0.05,
          percent_naval: 0.05,
          percent_orbital: 0.7,
          metal_drain_check: 0.54,
          energy_drain_check: 0.77,
          metal_demand_check: 0.95,
          energy_demand_check: 0.92,
          micro_type: 0,
          go_for_the_kill: false,
          neural_data_mod: 1.6,
          personality_tags: ["GWAlly", "SlowerExpansion"],
          adv_eco_mod: 0.5,
          adv_eco_mod_alone: 0,
          priority_scout_metal_spots: false,
          factory_build_delay_min: 0,
          factory_build_delay_max: 6,
          unable_to_expand_delay: 0,
          enable_commander_danger_responses: false,
          per_expansion_delay: 0,
          fabber_to_factory_ratio_basic: 5,
          fabber_to_factory_ratio_advanced: 1,
          fabber_alone_on_planet_mod: 1,
          basic_to_advanced_factory_ratio: 0,
          factory_alone_on_planet_mod: 1,
          min_basic_fabbers: 5,
          max_basic_fabbers: 10,
          min_advanced_fabbers: 3,
          max_advanced_fabbers: 10
        },
        commander: "/pa/units/commanders/tank_sadiga/tank_sadiga.json"
      }
    ] // minions
  };
});
