define({
  // Legonis Machina
  legonisMachina: {
    percent_vehicle: 0.65,
    percent_bot: 0.1,
    percent_air: 0.15,
    percent_naval: 0.05,
    percent_orbital: 0.05,
    metal_drain_check: 0.54,
    energy_drain_check: 0.65,
    metal_demand_check: 0.71,
    energy_demand_check: 0.8,
    micro_type: 0,
    go_for_the_kill: false,
    neural_data_mod: 1,
    personality_tags: [
      "Default",
      "GWAlly",
      "SlowerExpansion",
      "queller",
      "GalacticWar",
    ],
    adv_eco_mod: 1,
    adv_eco_mod_alone: 0.85,
    priority_scout_metal_spots: false,
    factory_build_delay_min: 0,
    factory_build_delay_max: 0,
    unable_to_expand_delay: 0,
    enable_commander_danger_responses: false,
    per_expansion_delay: 0,
    fabber_to_factory_ratio_basic: 1,
    fabber_to_factory_ratio_advanced: 1,
    fabber_alone_on_planet_mod: 2,
    basic_to_advanced_factory_ratio: 0,
    factory_alone_on_planet_mod: 0.5,
    min_basic_fabbers: 2,
    max_basic_fabbers: 4,
    min_advanced_fabbers: 3,
    max_advanced_fabbers: 3,
  },
  legonisMachinaBoss: {
    percent_naval: 0,
    percent_orbital: 0.1,
    micro_type: 2,
    go_for_the_kill: true,
    fabber_to_factory_ratio_basic: 2,
    fabber_to_factory_ratio_advanced: 2,
    fabber_alone_on_planet_mod: 3,
    min_basic_fabbers: 4,
    min_advanced_fabbers: 1,
  },
  legonisMachinaOriginal: {
    percent_vehicle: 0.275,
    percent_bot: 0.275,
    percent_air: 0.35,
    percent_naval: 0.05,
    percent_orbital: 0.05,
    metal_drain_check: 0.75,
    energy_drain_check: 0.85,
    metal_demand_check: 0.75,
    energy_demand_check: 0.85,
    fabber_to_factory_ratio_basic: 1.5,
    min_basic_fabbers: 1,
  },
  armour: {
    percent_vehicle: 1,
    percent_bot: 0,
    percent_air: 0,
    percent_naval: 0,
    percent_orbital: 0,
  },
  roboticist: {
    percent_vehicle: 0,
    percent_bot: 1,
    percent_air: 0,
    percent_naval: 0,
    percent_orbital: 0,
  },

  // Foundation
  foundation: {
    percent_vehicle: 0.2,
    percent_bot: 0.05,
    percent_air: 0.25,
    percent_naval: 0.45,
    percent_orbital: 0.05,
    metal_drain_check: 0.54,
    energy_drain_check: 0.65,
    metal_demand_check: 0.71,
    energy_demand_check: 0.8,
    micro_type: 0,
    go_for_the_kill: false,
    neural_data_mod: 1,
    personality_tags: [
      "Default",
      "GWAlly",
      "SlowerExpansion",
      "queller",
      "GalacticWar",
    ],
    adv_eco_mod: 1.3,
    adv_eco_mod_alone: 0.85,
    priority_scout_metal_spots: false,
    factory_build_delay_min: 0,
    factory_build_delay_max: 0,
    unable_to_expand_delay: 0,
    enable_commander_danger_responses: false,
    per_expansion_delay: 0,
    fabber_to_factory_ratio_basic: 1,
    fabber_to_factory_ratio_advanced: 2,
    fabber_alone_on_planet_mod: 2,
    basic_to_advanced_factory_ratio: 0,
    factory_alone_on_planet_mod: 0.5,
    min_basic_fabbers: 2,
    max_basic_fabbers: 4,
    min_advanced_fabbers: 3,
    max_advanced_fabbers: 3,
  },
  foundationBoss: {
    adv_eco_mod: 1,
    fabber_to_factory_ratio_basic: 2,
    fabber_to_factory_ratio_advanced: 2,
    fabber_alone_on_planet_mod: 3,
    min_basic_fabbers: 4,
    min_advanced_fabbers: 1,
  },
  foundationOriginal: {
    percent_vehicle: 0.025,
    percent_bot: 0.025,
    percent_air: 0.55,
    percent_naval: 0.35,
    percent_orbital: 0.05,
    metal_drain_check: 0.75,
    energy_drain_check: 0.85,
    metal_demand_check: 0.75,
    energy_demand_check: 0.85,
    fabber_to_factory_ratio_basic: 1.5,
    min_basic_fabbers: 1,
  },
  airForce: {
    percent_vehicle: 0,
    percent_bot: 0,
    percent_air: 1,
    percent_naval: 0,
    percent_orbital: 0,
  },
  navy: {
    percent_vehicle: 0,
    percent_bot: 0,
    percent_air: 0,
    percent_naval: 1,
    percent_orbital: 0,
  },

  //Synchronous
  synchronous: {
    percent_vehicle: 0.1,
    percent_bot: 0.65,
    percent_air: 0.15,
    percent_naval: 0.05,
    percent_orbital: 0.05,
    metal_drain_check: 0.54,
    energy_drain_check: 0.65,
    metal_demand_check: 0.71,
    energy_demand_check: 0.8,
    micro_type: 0,
    go_for_the_kill: false,
    neural_data_mod: 1,
    personality_tags: [
      "Default",
      "GWAlly",
      "SlowerExpansion",
      "queller",
      "GalacticWar",
    ],
    adv_eco_mod: 1.3,
    adv_eco_mod_alone: 0.85,
    priority_scout_metal_spots: false,
    factory_build_delay_min: 0,
    factory_build_delay_max: 0,
    unable_to_expand_delay: 0,
    enable_commander_danger_responses: false,
    per_expansion_delay: 0,
    fabber_to_factory_ratio_basic: 1.5,
    fabber_to_factory_ratio_advanced: 1,
    fabber_alone_on_planet_mod: 2,
    basic_to_advanced_factory_ratio: 0,
    factory_alone_on_planet_mod: 0.5,
    min_basic_fabbers: 2,
    max_basic_fabbers: 4,
    min_advanced_fabbers: 3,
    max_advanced_fabbers: 3,
  },
  synchronousBoss: {
    percent_naval: 0,
    percent_orbital: 0.1,
    adv_eco_mod: 1,
    fabber_to_factory_ratio_basic: 2,
    fabber_to_factory_ratio_advanced: 2,
    fabber_alone_on_planet_mod: 3,
    min_basic_fabbers: 4,
    min_advanced_fabbers: 1,
  },
  synchronousOriginal: {
    percent_vehicle: 0.15,
    percent_bot: 0.15,
    percent_air: 0.3,
    percent_naval: 0.05,
    percent_orbital: 0.35,
    min_basic_fabbers: 1,
  },
  grunt: {
    percent_vehicle: 0.4,
    percent_bot: 0.3,
    percent_air: 0.2,
    percent_naval: 0.05,
    percent_orbital: 0.05,
  },
  dragoon: {
    percent_vehicle: 0,
    percent_bot: 0.2,
    percent_air: 0.7,
    percent_naval: 0.05,
    percent_orbital: 0.05,
  },

  // Revenants
  revenants: {
    percent_vehicle: 0.25,
    percent_bot: 0.2,
    percent_air: 0.05,
    percent_naval: 0.05,
    percent_orbital: 0.45,
    metal_drain_check: 0.54,
    energy_drain_check: 0.65,
    metal_demand_check: 0.71,
    energy_demand_check: 0.8,
    micro_type: 0,
    go_for_the_kill: false,
    neural_data_mod: 1,
    personality_tags: [
      "Default",
      "GWAlly",
      "SlowerExpansion",
      "queller",
      "GalacticWar",
    ],
    adv_eco_mod: 1.3,
    adv_eco_mod_alone: 0.85,
    priority_scout_metal_spots: false,
    factory_build_delay_min: 0,
    factory_build_delay_max: 0,
    unable_to_expand_delay: 0,
    enable_commander_danger_responses: false,
    per_expansion_delay: 0,
    fabber_to_factory_ratio_basic: 1,
    fabber_to_factory_ratio_advanced: 1,
    fabber_alone_on_planet_mod: 3,
    basic_to_advanced_factory_ratio: 0,
    factory_alone_on_planet_mod: 0.25,
    min_basic_fabbers: 2,
    max_basic_fabbers: 4,
    min_advanced_fabbers: 3,
    max_advanced_fabbers: 3,
  },
  revenantsBoss: {
    adv_eco_mod: 1,
    fabber_to_factory_ratio_basic: 2,
    fabber_to_factory_ratio_advanced: 2,
    fabber_alone_on_planet_mod: 3,
    min_basic_fabbers: 4,
    min_advanced_fabbers: 1,
  },
  revenantsOriginal: {
    percent_vehicle: 0.075,
    percent_bot: 0.075,
    percent_air: 0.15,
    percent_naval: 0.1,
    percent_orbital: 0.6,
    fabber_to_factory_ratio_basic: 1.5,
    min_basic_fabbers: 1,
  },
  spaceInvader: {
    percent_vehicle: 0,
    percent_bot: 0,
    percent_air: 0,
    percent_naval: 0,
    percent_orbital: 1,
  },
  astronaut: {
    percent_vehicle: 0,
    percent_bot: 0,
    percent_air: 0.5,
    percent_naval: 0,
    percent_orbital: 0.5,
  },

  // Cluster
  cluster: {
    percent_vehicle: 0.45,
    percent_bot: 0.4,
    percent_air: 0.05,
    percent_naval: 0.05,
    percent_orbital: 0.05,
    metal_drain_check: 0.54,
    energy_drain_check: 0.65,
    metal_demand_check: 0.71,
    energy_demand_check: 0.8,
    micro_type: 0,
    go_for_the_kill: false,
    neural_data_mod: 1,
    personality_tags: [
      "Default",
      "GWAlly",
      "SlowerExpansion",
      "queller",
      "GalacticWar",
    ],
    adv_eco_mod: 1.5,
    adv_eco_mod_alone: 0.85,
    priority_scout_metal_spots: false,
    factory_build_delay_min: 0,
    factory_build_delay_max: 0,
    unable_to_expand_delay: 0,
    enable_commander_danger_responses: false,
    per_expansion_delay: 0,
    fabber_to_factory_ratio_basic: 1,
    fabber_to_factory_ratio_advanced: 1,
    fabber_alone_on_planet_mod: 2,
    basic_to_advanced_factory_ratio: 0,
    factory_alone_on_planet_mod: 0.5,
    min_basic_fabbers: 3,
    max_basic_fabbers: 4,
    min_advanced_fabbers: 1,
    max_advanced_fabbers: 3,
  },
  clusterBoss: {
    adv_eco_mod: 2,
    fabber_to_factory_ratio_basic: 1.5,
    fabber_alone_on_planet_mod: 3,
    min_basic_fabbers: 4,
  },

  // Generic
  uber: {
    energy_drain_check: 0.72,
    metal_demand_check: 0.8,
    fabber_to_factory_ratio_advanced: 2,
    fabber_alone_on_planet_mod: 3,
    min_basic_fabbers: 3,
    min_advanced_fabbers: 1,
  },
  fabber: {
    fabber_to_factory_ratio_basic: 2,
    fabber_to_factory_ratio_advanced: 2,
    factory_alone_on_planet_mod: 0.25,
  },
  defender: {
    metal_drain_check: 0.71,
    energy_drain_check: 0.8,
    metal_demand_check: 0.54,
    energy_demand_check: 0.65,
    adv_eco_mod: 1,
    min_basic_fabbers: 4,
  },
  luddite: {
    adv_eco_mod: 3,
    adv_eco_mod_alone: 2,
  },
  technologist: {
    adv_eco_mod: 0.5,
    adv_eco_mod_alone: 0.5,
    fabber_to_factory_ratio_basic: 3,
    min_basic_fabbers: 4,
    min_advanced_fabbers: 1,
  },
  cautious: {
    neural_data_mod: 0.75,
    min_basic_fabbers: 4,
  },
  aggressive: {
    neural_data_mod: 2,
    min_basic_fabbers: 2,
    min_advanced_fabbers: 1,
  },
  rush: {
    neural_data_mod: 1.5,
    adv_eco_mod: 2,
    min_basic_fabbers: 2,
    min_advanced_fabbers: 1,
  },
  turtle: {
    neural_data_mod: 0.5,
    adv_eco_mod: 0.5,
    adv_eco_mod_alone: 0.5,
    fabber_to_factory_ratio_basic: 3,
    fabber_to_factory_ratio_advanced: 3,
    min_basic_fabbers: 4,
    max_basic_fabbers: 8,
    max_advanced_fabbers: 6,
  },
  absurd: {
    adv_eco_mod: 1.3,
    min_basic_fabbers: 2,
    min_advanced_fabbers: 3,
  },
  factory: {
    fabber_to_factory_ratio_basic: 0.5,
    fabber_to_factory_ratio_advanced: 0.5,
    metal_demand_check: 0.99,
    energy_demand_check: 0.99,
  },
  swarm: {
    basic_to_advanced_factory_ratio: 10,
    fabber_to_factory_ratio_advanced: 3,
  },
  economist: {
    metal_drain_check: 0.71,
    energy_drain_check: 0.8,
    metal_demand_check: 0.99,
    energy_demand_check: 0.99,
    adv_eco_mod: 1,
    min_basic_fabbers: 4,
  },
});
